# ILANG
# TYPE:module ROLE:builder PROJECT:vps-deals
# ::RULE{配置与文案参数来自 .ilang/site.ilang 和 data/offers.json⇒不许在代码里另写一份}
# ::RULE{没有 price 的优惠⇒页面照常列 但不写 price 也不写 priceCurrency 进结构化数据}
# ::RULE{每页必须有 canonical 和 JSON-LD⇒sitemap.xml 和 robots.txt 由本文件生成 不手写}
# ::RULE{标题和描述由数据生成⇒带厂商名 价格 和当前月份 不许所有页共用一句模板}
# ::BOUNDARY{never:编价格 编有效期 编评分|scope:file}
"""读 data/offers.json -> 渲染静态站到 site/（含 JSON-LD、canonical、sitemap）

零依赖：只用 Python 标准库。
用法：python build.py
"""

from __future__ import annotations

import json
import re
import struct
import zlib
from datetime import datetime, timezone
from html import escape
from pathlib import Path

from scraper import load_config

ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "data" / "offers.json"
GUIDES_PATH = ROOT / "data" / "guides.json"
TEMPLATE_DIR = ROOT / "templates"
ASSET_DIR = TEMPLATE_DIR / "assets"
SITE_DIR = ROOT / "site"

SYMBOLS = {"USD": "$", "EUR": "€", "GBP": "£"}
MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# Cloudflare Pages 高级模式脚本：放在输出目录里，全量接管请求。
# ::_redirects 不支持域名级跳转（官方文档 Domain-level redirects ❌），
# ::所以 *.pages.dev（含预览哈希地址）这类非规范主机名必须在这里 301 到主域名，
# ::避免同一个站有两个地址并存、把权重分散掉。主域名请求照常走静态资源。
WORKER_TEMPLATE = """// ILANG
// TYPE:worker ROLE:canonical-host-and-real-404
// ::RULE{non-canonical hosts get a 301 to the canonical domain; never leave two live addresses}
// ::RULE{paths outside the allow-list get a real 404; never let Pages fall back to the homepage}
// ::RULE{the allow-list is generated by build.py, so adding a page needs no edit here}
// ::BOUNDARY{never:render content from this file|scope:file}
const CANONICAL_HOST = "__CANONICAL_HOST__";
const VALID_PATHS = new Set(__VALID_PATHS__);

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.hostname !== CANONICAL_HOST) {
      return Response.redirect(new URL(url.pathname + url.search, `https://${CANONICAL_HOST}`).toString(), 301);
    }

    const path = url.pathname.replace(/\\/+$/, "") || "/";

    // Legacy /xxx.html addresses from earlier deploys: permanent redirect to the clean path
    if (path.endsWith(".html")) {
      const bare = path === "/index.html" ? "/" : path.slice(0, -5);
      if (VALID_PATHS.has(bare)) {
        return Response.redirect(new URL(bare + url.search, `https://${CANONICAL_HOST}`).toString(), 308);
      }
    }

    if (VALID_PATHS.has(path)) {
      return env.ASSETS.fetch(request);
    }

    // Cloudflare Pages answers unmatched paths with the homepage and a 200.
    // Turn that into a real 404: search engines and reviewers should not see a valid page
    // at an address that does not exist.
    const notFound = await env.ASSETS.fetch(new URL("/404.html", url));
    return new Response(notFound.body, {
      status: 404,
      headers: {
        "content-type": "text/html; charset=utf-8",
        "cache-control": "no-store",
        "x-robots-tag": "noindex",
      },
    });
  },
};
"""


# ------------------------------------------------------------------ 小工具

def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "item"


# Cloudflare Pages 会把 /x.html 308 跳到 /x，所以 canonical 和 sitemap 一律用干净 URL，
# 文件本身仍然写成 .html —— 让被索引的地址就是最终地址，避免 canonical 指向一个跳转。
def home_url(site: dict) -> str:
    return f'{site["base_url"]}/'


def compare_url(site: dict) -> str:
    return f'{site["base_url"]}/compare'


def provider_page(site: dict, name: str) -> str:
    return f'{site["base_url"]}/provider/{slugify(name)}'


def deal_page(site: dict, offer: dict) -> str:
    return f'{site["base_url"]}/deal/{offer_slug(offer)}'


def render(template: str, values: dict[str, str]) -> str:
    def replace(match: re.Match) -> str:
        key = match.group(1).strip()
        return values.get(key, "")

    return re.sub(r"\{\{\s*([a-zA-Z0-9_]+)\s*\}\}", replace, template)


def template(name: str) -> str:
    html = (TEMPLATE_DIR / name).read_text(encoding="utf-8")
    # 样式统一收在 assets/style.css 一份；模板里若有历史内联 <style> 一律剥掉，
    # 否则内联样式会盖掉新设计（同权重下后出现的胜出）。
    return re.sub(r"\s*<style>.*?</style>", "", html, flags=re.S)


def money(price: float | None, currency: str) -> str:
    if price is None:
        return ""
    symbol = SYMBOLS.get(currency, "")
    amount = f"{price:.2f}".rstrip("0").rstrip(".") if price % 1 else f"{price:.0f}"
    return f"{symbol}{amount} {currency}" if not symbol else f"{symbol}{amount}"


def jsonld(payload: dict | list) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def iso_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------- 社交分享大图
# 社交平台不接受 SVG，所以这张 OG 图在构建时用纯标准库自己写成 PNG：
# 没有 Pillow、没有外部服务，画的还是那套像素字和那只猫。
PIXEL_FONT = {
    "V": ["#...#", "#...#", "#...#", "#...#", "#...#", ".#.#.", "..#.."],
    "P": ["####.", "#...#", "#...#", "####.", "#....", "#....", "#...."],
    "S": [".####", "#....", "#....", ".###.", "....#", "....#", "####."],
    "D": ["###..", "#..#.", "#...#", "#...#", "#...#", "#..#.", "###.."],
    "E": ["#####", "#....", "#....", "####.", "#....", "#....", "#####"],
    "A": ["..#..", ".#.#.", "#...#", "#####", "#...#", "#...#", "#...#"],
    "L": ["#....", "#....", "#....", "#....", "#....", "#....", "#####"],
    "R": ["####.", "#...#", "#...#", "####.", "#.#..", "#..#.", "#...#"],
    " ": [".....", ".....", ".....", ".....", ".....", ".....", "....."],
}
CAT_ART = [
    "....##......##....",
    "...####....####...",
    "...####....####...",
    "..##############..",
    "..##############..",
    "..##..######..##..",
    "..##..######..##..",
    "..##############..",
    "..####..####..##..",
    "..##############..",
    "...############...",
    "....##########....",
    "...############...",
    "..##############..",
    "..##############..",
    "...############...",
]


def _png_bytes(width: int, height: int, pixels: list) -> bytes:
    """极简 PNG 编码器（8 位 RGB、无滤波），只依赖 zlib 与 struct。"""
    raw = bytearray()
    for row in pixels:
        raw.append(0)
        for rgb in row:
            raw.extend(rgb)
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


def build_og_image(site: dict, path: Path) -> None:
    W, H = 1200, 630
    bg, panel, accent, fur, ink, line = (10, 13, 19), (18, 25, 38), (246, 130, 31), (238, 242, 248), (20, 28, 40), (33, 44, 61)
    pixels = [[bg for _ in range(W)] for _ in range(H)]

    def fill(x0, y0, w, h, colour):
        for y in range(max(0, y0), min(H, y0 + h)):
            row = pixels[y]
            for x in range(max(0, x0), min(W, x0 + w)):
                row[x] = colour

    # 轻微渐变的底 + 左侧强调色竖条
    for y in range(H):
        shade = 14 + int(10 * (1 - y / H))
        row = pixels[y]
        for x in range(W):
            row[x] = (bg[0] + shade // 3, bg[1] + shade // 2, bg[2] + shade)
    fill(0, 0, 14, H, accent)

    # 像素字：VPS DEALS RADAR（放在猫下面，缩到不会溢出右边缘）
    text = "VPS DEALS RADAR"
    scale, gap = 8, 3
    gw, gh = 5 * scale, 7 * scale
    total = len(text) * gw + (len(text) - 1) * gap
    x = (W - total) // 2
    y = 372
    for ch in text:
        glyph = PIXEL_FONT.get(ch, PIXEL_FONT[" "])
        for gy, row in enumerate(glyph):
            for gx, dot in enumerate(row):
                if dot == "#":
                    fill(x + gx * scale, y + gy * scale, scale, scale, fur)
        x += gw + gap

    # 那只猫（16x16 像素画，放大 11 倍，放在上半部）
    cat_scale = 11
    cat_w, cat_h = 16 * cat_scale, 16 * cat_scale
    cx, cy = (W - cat_w) // 2, 118
    for gy, row in enumerate(CAT_ART):
        for gx, dot in enumerate(row):
            if dot == "#":
                fill(cx + gx * cat_scale, cy + gy * cat_scale, cat_scale, cat_scale, fur)
    # 耳朵内侧 + 眼睛 + 鼻子 + 领圈（与页面上那只同一套配色）
    fill(cx + 3 * cat_scale, cy + 1 * cat_scale, cat_scale, 2 * cat_scale, accent)
    fill(cx + 12 * cat_scale, cy + 1 * cat_scale, cat_scale, 2 * cat_scale, accent)
    fill(cx + 3 * cat_scale, cy + 5 * cat_scale, 2 * cat_scale, 2 * cat_scale, ink)
    fill(cx + 9 * cat_scale, cy + 5 * cat_scale, 2 * cat_scale, 2 * cat_scale, ink)
    fill(cx + 7 * cat_scale, cy + 8 * cat_scale, 2 * cat_scale, cat_scale, accent)
    fill(cx, cy + 12 * cat_scale, cat_w, cat_scale, accent)

    # 底部一条分隔线
    fill(0, H - 96, W, 2, line)
    path.write_bytes(_png_bytes(W, H, pixels))


# 静态资产的缓存版本号：每次构建都不同，访客不会拿到上一版的 css/js。
# 在 main() 里按数据快照时间赋值。
ASSET_V = "0"

# 站点验证与统计：来自 .ilang/site.ilang 的 @SITE 状态；留空即不注入。
VERIFY: dict[str, str] = {"gsc": "", "ga4": ""}


# ------------------------------------------------------------------ 数据整理

def group_offers(offers: list[dict]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for offer in offers:
        grouped.setdefault(offer["provider"], []).append(offer)
    for rows in grouped.values():
        rows.sort(key=lambda row: (row.get("price") is None, row.get("price") or 0))
    return grouped


def collapse_offers(offers: list[dict]) -> tuple[list[dict], dict[tuple, int]]:
    """同一家厂商同一个套餐名可能公布多个价格（原价/促销价）。

    塌缩成一条（保留更低那个），并记录公布了几个价格，供页面如实说明。
    不合并的话 slug 会撞车：一个页面被另一个覆盖，sitemap 还会出现重复 URL。
    """
    best: dict[tuple, dict] = {}
    variants: dict[tuple, int] = {}
    for offer in offers:
        key = (offer["provider"], offer["title"].lower())
        variants[key] = variants.get(key, 0) + 1
        current = best.get(key)
        if current is None:
            best[key] = dict(offer)
            continue
        if offer.get("price") is not None and (
            current.get("price") is None or offer["price"] < current["price"]
        ):
            current["price"] = offer["price"]
            current["currency"] = offer.get("currency", current.get("currency"))
        if offer.get("valid_until") and not current.get("valid_until"):
            current["valid_until"] = offer["valid_until"]
    return list(best.values()), variants


def offer_slug(offer: dict) -> str:
    return slugify(f"{offer['provider']}-{offer['title']}")


def affiliate_for(offer: dict, providers: dict[str, dict]) -> str:
    """联盟链接优先；site.ilang 里留空就用抓到的裸链。"""
    provider = providers.get(offer["provider"], {})
    return provider.get("affiliate_url") or offer["offer_url"]


# ------------------------------------------------------------------ 头部与骨架

def head_block(meta: dict, extra_jsonld: list[dict] | None = None) -> str:
    links = [
        f'<link rel="canonical" href="{escape(meta["canonical"])}">',
        f'<link rel="alternate" hreflang="{escape(meta["locale"])}" href="{escape(meta["canonical"])}">',
        f'<link rel="alternate" hreflang="x-default" href="{escape(meta["canonical"])}">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<meta name="robots" content="index,follow,max-image-preview:large">',
        f'<link rel="stylesheet" href="/assets/style.css?v={ASSET_V}">',
        f'<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg?v={ASSET_V}">',
        f'<script src="/assets/pets.js?v={ASSET_V}" defer></script>',
    ]
    # 站点验证与统计只在配置里填了值时才出现；留空时页面里干干净净，隐私政策也照实说没有。
    if VERIFY.get("gsc"):
        links.append(f'<meta name="google-site-verification" content="{escape(VERIFY["gsc"])}">')
    if VERIFY.get("ga4"):
        gid = escape(VERIFY["ga4"])
        links.append(f'<script async src="https://www.googletagmanager.com/gtag/js?id={gid}"></script>')
        links.append(
            "<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}"
            f"gtag('js',new Date());gtag('config','{gid}');</script>"
        )
    social = [
        f'<meta property="og:type" content="{escape(meta["og_type"])}">',
        f'<meta property="og:title" content="{escape(meta["title"])}">',
        f'<meta property="og:description" content="{escape(meta["description"])}">',
        f'<meta property="og:url" content="{escape(meta["canonical"])}">',
        f'<meta property="og:site_name" content="{escape(meta["brand"])}">',
        f'<meta property="og:image" content="{escape(meta["og_image"])}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{escape(meta["title"])}">',
        f'<meta name="twitter:description" content="{escape(meta["description"])}">',
        f'<meta name="twitter:image" content="{escape(meta["og_image"])}">',
        f'<meta name="description" content="{escape(meta["description"])}">',
    ]
    blocks = [f'<script type="application/ld+json">{jsonld(item)}</script>' for item in (extra_jsonld or [])]
    return "\n  ".join(links + social + blocks)


def nav_block(site: dict, providers: list[dict]) -> str:
    links = [f'<a href="{escape(home_url(site))}">Home</a>']
    links.append(f'<a href="{escape(compare_url(site))}">Compare all</a>')
    for provider in providers:
        links.append(
            f'<a href="{escape(provider_page(site, provider["name"]))}">{escape(provider["name"])}</a>'
        )
    return " · ".join(links)


def footer_block(site: dict, generated_at: str) -> str:
    nav_links = " · ".join(
        [
            f'<a href="{escape(site["base_url"])}/about">About</a>',
            f'<a href="{escape(site["base_url"])}/privacy">Privacy Policy</a>',
            f'<a href="{escape(site["base_url"])}/contact">Contact</a>',
            f'<a href="{escape(site["base_url"])}/sitemap.xml">Sitemap</a>',
        ]
    )
    return (
        f'<p class="muted">Prices are read from each provider\'s own public page on {escape(generated_at)} '
        "and can change without notice — always confirm on the provider site before buying.</p>"
        '<p class="muted">Independent listings. No invented prices: a plan without a published price shows no price.</p>'
        '<p class="muted"><strong>Third-party advertising:</strong> this site displays third-party advertising.</p>'
        '<p class="muted"><strong>Affiliate links:</strong> some outbound links are affiliate links.</p>'
        '<p class="muted"><strong>Commission:</strong> if you sign up through one of those links, we may earn a commission.</p>'
        f'<p class="muted">{escape(site["brand"])} · {nav_links}</p>'
        # 像素小动物的挂载点：纯装饰，画布由 assets/pets.js 生成。
        # 放在页脚里是因为页脚每页都有；它是 position:fixed，不影响版式。
        '<div class="critter" aria-hidden="true"></div>'
    )


# ------------------------------------------------------------------ 渲染各页

def offer_rows(offers: list[dict], site: dict, providers: dict[str, dict], with_provider: bool) -> str:
    rows = []
    for offer in offers:
        price = money(offer.get("price"), offer.get("currency", "USD"))
        price_cell = price if price else '<span class="muted">not published</span>'
        provider_cell = (
            f'<a href="{escape(provider_page(site, offer["provider"]))}">{escape(offer["provider"])}</a>'
            if with_provider
            else ""
        )
        detail = deal_page(site, offer)
        target = affiliate_for(offer, providers)
        rows.append(
            "<tr>"
            f"<td>{provider_cell}</td>"
            f'<td><a href="{escape(detail)}">{escape(offer["title"])}</a></td>'
            f'<td class="price">{price_cell}</td>'
            f'<td><a class="btn" rel="nofollow sponsored noopener" target="_blank" href="{escape(target)}">View on provider</a></td>'
            "</tr>"
        )
    return "\n".join(rows)


def build_index(site: dict, offers: list[dict], providers: list[dict], generated_at: str) -> str:
    grouped = group_offers(offers)
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    priced = [o for o in offers if o.get("price")]
    cheapest = min(priced, key=lambda o: o["price"]) if priced else None
    title = f"{site['title']} — {len(offers)} live VPS deals tracked ({month} {datetime.now(timezone.utc).year})"
    description = (
        f"{len(offers)} VPS plans tracked across {len(grouped)} providers, prices read straight from each "
        f"provider's public page. Updated {generated_at}."
    )
    if cheapest:
        description += f" Cheapest tracked plan: {cheapest['provider']} {cheapest['title']} at {money(cheapest['price'], cheapest.get('currency','USD'))}."

    cards = []
    for provider in providers:
        rows = grouped.get(provider["name"], [])
        if not rows:
            note = provider.get("note") or "no published price found on the source page"
            cards.append(
                f'<div class="card"><h3>{escape(provider["name"])}</h3>'
                f'<p class="muted">Tracked, but {escape(note)}.</p>'
                f'<p><a href="{escape(provider["homepage"])}" rel="nofollow noopener" target="_blank">Official site</a></p></div>'
            )
            continue
        lowest = rows[0]
        cards.append(
            f'<div class="card"><h3><a href="{escape(provider_page(site, provider["name"]))}">'
            f'{escape(provider["name"])}</a></h3>'
            f'<p class="price big">{escape(money(lowest.get("price"), lowest.get("currency","USD")))}</p>'
            f'<p class="muted">from {escape(lowest["title"])} · {len(rows)} plans tracked</p></div>'
        )

    item_list = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": title,
        "itemListElement": [
            {"@type": "ListItem", "position": index + 1,
             "url": deal_page(site, offer), "name": f'{offer["provider"]} {offer["title"]}'}
            for index, offer in enumerate(offers[:50])
        ],
    }
    website = {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": site["title"],
        "url": home_url(site),
        "description": description,
    }
    meta = {
        "canonical": home_url(site),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }
    return render(
        template("index.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [website, item_list]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "tagline": escape(site["tagline"]),
            "generated_at": generated_at,
            "cards": "\n".join(cards),
            "rows": offer_rows(offers[:60], site, {}, True),
            "offer_count": str(len(offers)),
            "provider_count": str(len(grouped)),
        },
    )


def build_provider(site: dict, provider: dict, offers: list[dict], generated_at: str) -> str:
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    name = provider["name"]
    priced = [o for o in offers if o.get("price")]
    low = min((o["price"] for o in priced), default=None)
    high = max((o["price"] for o in priced), default=None)
    currency = offers[0].get("currency", provider.get("currency", "USD")) if offers else provider.get("currency", "USD")

    title = f"{name} VPS prices ({month} {datetime.now(timezone.utc).year}) — {len(offers)} plans tracked"
    description = (
        f"{name} VPS plans with prices read from the provider's public page on {generated_at}. "
        + (f"{len(priced)} of {len(offers)} plans publish a price; from {money(low, currency)}." if priced
           else "No price is published in machine-readable form on that page, so this page lists plan names only.")
    )
    graphs: list[dict] = [
        {
            "@context": "https://schema.org",
            "@type": "Product",
            "name": f"{name} VPS plans",
            "url": provider_page(site, name),
            "brand": {"@type": "Brand", "name": name},
        }
    ]
    if priced:
        graphs[0]["offers"] = {
            "@type": "AggregateOffer",
            "priceCurrency": currency,
            "lowPrice": low,
            "highPrice": high,
            "offerCount": len(priced),
            "availability": "https://schema.org/InStock",
            "url": provider_page(site, name),
        }
    graphs.append(
        {
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": site["title"], "item": home_url(site)},
                {"@type": "ListItem", "position": 2, "name": name, "item": provider_page(site, name)},
            ],
        }
    )
    meta = {
        "canonical": provider_page(site, name),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }
    return render(
        template("provider.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, graphs),
            "nav": nav_block(site, [provider]),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "provider": escape(name),
            "homepage": escape(provider["homepage"]),
            "source_url": escape(provider["deals_url"]),
            "generated_at": generated_at,
            "rows": offer_rows(offers, site, {}, False) or '<tr><td colspan="4" class="muted">No plan with a published price was found on the source page.</td></tr>',
            "low": money(low, currency) if low else "",
            "high": money(high, currency) if high else "",
            "offer_count": str(len(offers)),
            "priced_count": str(len(priced)),
            "note": escape(provider.get("note") or ""),
        },
    )


def build_deal(site: dict, offer: dict, generated_at: str, variants: int = 1) -> str:
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    currency = offer.get("currency", "USD")
    price_text = money(offer.get("price"), currency)
    title = f'{offer["provider"]} {offer["title"]}' + (f' — {price_text} ({month})' if price_text else f' ({month})')
    description = (
        f'{offer["provider"]} {offer["title"]}'
        + (f' listed at {price_text}' if price_text else ' (no published price found)')
        + f'. Read from {offer["source_url"]} on {offer["fetched_at"]}.'
    )
    schema: dict = {
        "@context": "https://schema.org",
        "@type": "Offer",
        "name": f'{offer["provider"]} {offer["title"]}',
        "url": deal_page(site, offer),
        "availability": "https://schema.org/InStock",
        "seller": {"@type": "Organization", "name": offer["provider"]},
        "priceSpecification": {"@type": "UnitPriceSpecification", "referenceQuantity": {"@type": "QuantitativeValue", "unitCode": "MON"}},
    }
    if offer.get("price") is not None:
        schema["price"] = offer["price"]
        schema["priceCurrency"] = currency
    if offer.get("valid_until"):
        schema["priceValidUntil"] = offer["valid_until"]
    breadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": site["title"], "item": home_url(site)},
            {"@type": "ListItem", "position": 2, "name": offer["provider"],
             "item": provider_page(site, offer["provider"])},
            {"@type": "ListItem", "position": 3, "name": offer["title"], "item": deal_page(site, offer)},
        ],
    }
    meta = {
        "canonical": deal_page(site, offer),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "product",
        "og_image": site["og_image"],
    }
    return render(
        template("deal.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [schema, breadcrumb]),
            "nav": nav_block(site, []),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "deal_title": escape(offer["title"]),
            "provider": escape(offer["provider"]),
            "provider_url": provider_page(site, offer["provider"]),
            "price": escape(price_text) if price_text else '<span class="muted">not published on the source page</span>',
            "currency": escape(currency),
            "valid_until": escape(offer.get("valid_until", "")) or '<span class="muted">not stated</span>',
            "source_url": escape(offer["source_url"]),
            "fetched_at": escape(offer["fetched_at"]),
            "offer_url": escape(offer["offer_url"]),
            "variants_note": (
                f'The provider page currently lists {variants} different prices for this plan; the lowest is shown here.'
                if variants > 1
                else ""
            ),
        },
    )


def build_compare(site: dict, offers: list[dict], providers: list[dict], generated_at: str) -> str:
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    title = f"Compare {len(offers)} VPS plans by price ({month} {datetime.now(timezone.utc).year})"
    description = (
        f"Side-by-side price list of {len(offers)} VPS plans tracked from provider pages, sorted cheapest first. "
        f"Last read {generated_at}. Prices shown are the numbers published on each provider page."
    )
    item_list = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": title,
        "itemListElement": [
            {"@type": "ListItem", "position": index + 1,
             "url": deal_page(site, offer),
             "name": f'{offer["provider"]} {offer["title"]}'}
            for index, offer in enumerate(offers)
        ],
    }
    meta = {
        "canonical": compare_url(site),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }
    return render(
        template("compare.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [item_list]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "generated_at": generated_at,
            "rows": offer_rows(offers, site, {}, True),
            "offer_count": str(len(offers)),
        },
    )


# ------------------------------------------------------------------ 指南栏（补前十三页的缺口）

def guides_url(site: dict) -> str:
    return f'{site["base_url"]}/guide'


def guide_page(site: dict, guide: dict) -> str:
    return f'{site["base_url"]}/guide/{guide["slug"]}'


def _csv_cell(value) -> str:
    text = "" if value is None else str(value)
    if any(ch in text for ch in ',"\n'):
        return '"' + text.replace('"', '""') + '"'
    return text


def build_unit_price_csv(offers: list[dict]) -> tuple[str, int]:
    """可下载的比价表：每行一个套餐，规格和单价都来自抓到的公开页面。

    ::RULE{分母必须有出处⇒ram_gb / vcpu 缺失的行不写单价 写 not published}
    ::RULE{不换算货币⇒价格按源页面原币种原样输出}
    """
    header = [
        "provider", "plan", "price", "currency", "ram_gb", "vcpu", "disk_gb",
        "price_per_gb_ram", "price_per_vcpu", "unit_price_formula",
        "source_url", "fetched_at",
    ]
    lines = [",".join(header)]
    rows = 0
    for offer in sorted(offers, key=lambda o: (o["provider"], o.get("price") or 0)):
        price = offer.get("price")
        ram = offer.get("ram_gb")
        vcpu = offer.get("vcpu")
        per_gb = round(price / ram, 4) if price and ram else None
        per_vcpu = round(price / vcpu, 4) if price and vcpu else None
        formula = ""
        if per_gb is not None:
            formula = f'{price} {offer.get("currency", "")} / {ram} GB RAM'
        elif per_vcpu is not None:
            formula = f'{price} {offer.get("currency", "")} / {vcpu} vCPU'
        lines.append(",".join(_csv_cell(v) for v in [
            offer["provider"], offer["title"], price, offer.get("currency", ""),
            ram, vcpu, offer.get("disk_gb"), per_gb, per_vcpu, formula,
            offer["source_url"], offer["fetched_at"],
        ]))
        rows += 1
    return "\n".join(lines) + "\n", rows


def build_guide_index(
    site: dict, guides: list[dict], offers: list[dict], providers: list[dict], generated_at: str
) -> str:
    title = f'Cheap VPS guides — downloadable comparison table, unit prices, setup steps ({site["title"]})'
    description = (
        f"{len(guides)} ordered walkthroughs that fill what the top-ranking pages leave out: "
        "a comparison table you can download, prices broken down per GB of RAM and per vCPU, and numbered setup steps."
    )
    cards = []
    for guide in guides:
        cards.append(
            f'<div class="card"><h3><a href="{escape(guide_page(site, guide))}">{escape(guide["title"])}</a></h3>'
            f'<p class="muted">{escape(guide["answer"])}</p>'
            f'<p class="muted">gap filled: {escape(guide["gap"])}</p></div>'
        )
    offer_count = len([o for o in offers if o.get("price")])
    meta = _page_meta(site, "/guide", title, description)
    return render(
        template("guide.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, "/guide", title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "h1": escape(f"Cheap VPS guides ({len(guides)})"),
            "answer": (
                f'<p class="lede">Each guide answers one question on this page. '
                f'Across {offer_count} tracked plans with a published price, here is what the provider pages '
                f'themselves do not tell you.</p>'
                f'<p><a class="cta" href="{escape(site["base_url"])}/downloads/unit-price.csv">Download the comparison table (CSV)</a></p>'
            ),
            "body": f'<div class="grid">{"".join(cards)}</div>',
            "gap_note": "This index fills nothing by itself; each guide below fills exactly one gap.",
            "sources": '<p class="muted">Sources: each guide lists its own.</p>',
        },
    )


def answer_from_data(guide: dict, offers: list[dict]) -> str:
    """第一屏的答案必须带可核对的数字，数字只能来自抓到的数据。

    ::RULE{lede 里出现的每个数都能在 offers.json 或 CSV 里复算出来}
    自动页（guides.py 生成）自己带着按主题算好的答案，直接用；
    手写页没有当日主题，这里按缺口类型给一个汇总口径的答案。
    """
    if guide.get("auto") and guide.get("answer"):
        return guide["answer"]
    priced = [o for o in offers if o.get("price") is not None]
    with_ram = [o for o in priced if o.get("ram_gb")]
    ranked = sorted(with_ram, key=lambda o: o["price"] / o["ram_gb"])
    providers = len({o["provider"] for o in priced})
    gap = guide.get("gap")
    if gap == "csv":
        return (
            f"{len(priced)} tracked plans across {providers} providers; {len(with_ram)} of them publish the RAM "
            f"figure their price is quoted next to, so those rows carry a computed per-GB number. "
            f"The CSV hands over the table itself."
        )
    if gap == "unitprice" and ranked:
        best = ranked[0]
        return (
            f"Cheapest RAM per unit today is {best['provider']} {best['title']} at "
            f"{best['price'] / best['ram_gb']:.4f} {best.get('currency', '')} per GB "
            f"({best['price']} {best.get('currency', '')} / {best['ram_gb']} GB) — computed only from numbers the "
            f"provider published. {len(with_ram)} of {len(priced)} priced plans can be ranked at all."
        )
    if gap == "steps":
        cheapest = min(priced, key=lambda o: o["price"]) if priced else None
        cheapest_text = money(cheapest["price"], cheapest.get("currency", "USD")) if cheapest else "n/a"
        return (
            f"{len(priced)} tracked plans, cheapest at {cheapest_text} per month "
            f"({cheapest['provider']} {cheapest['title']}). Eight numbered steps from picking the plan to "
            f"logging in, each sourced to provider documentation."
            if cheapest
            else "No tracked plan currently publishes a price, so no step cost can be quoted."
        )
    return guide["answer"]


def build_guide(
    site: dict, guide: dict, offers: list[dict], providers: list[dict], generated_at: str
) -> str:
    # 每一篇只补一个缺口，正文在 data/guides.json 里给定（自动页由 guides.py 生成）。
    # 这里不再按 gap 现编内容，避免出现"同一份数据被渲染成两种说法"。
    body = guide.get("body_html", "")
    if re.search(r'href="[^"]*(/deal/|source_url)', body):
        raise SystemExit(f'guide {guide["slug"]} must not link to per-offer pages; bodies stay data-free')
    if not body:
        raise SystemExit(f'guide {guide["slug"]} has no body_html; refusing to publish an empty page')

    title = f'{guide["title"]} — {site["title"]}'
    meta = {
        "canonical": guide_page(site, guide),
        "locale": site["locale"],
        "title": title,
        "description": guide["answer"],
        "brand": site["brand"],
        "og_type": "article",
        "og_image": site["og_image"],
    }
    article = {
        "@context": "https://schema.org",
        "@type": "TechArticle",
        "headline": guide["title"],
        "description": guide["answer"],
        "url": guide_page(site, guide),
        "datePublished": generated_at[:10],
        "isPartOf": {"@type": "WebSite", "name": site["title"], "url": home_url(site)},
    }
    breadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": site["title"], "item": home_url(site)},
            {"@type": "ListItem", "position": 2, "name": "Guides", "item": guides_url(site)},
            {"@type": "ListItem", "position": 3, "name": guide["title"], "item": guide_page(site, guide)},
        ],
    }
    sources = "".join(
        f'<li><a href="{escape(item["url"])}" rel="nofollow noopener" target="_blank">{escape(item["label"])}</a>'
        f' — read {escape(generated_at)}</li>'
        for item in guide.get("sources", [])
    )
    return render(
        template("guide.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [article, breadcrumb]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "h1": escape(guide["title"]),
            "answer": f'<p class="lede">{escape(answer_from_data(guide, offers))}</p>',
            "body": body,
            "gap_note": escape(guide["gap_note"]),
            "sources": f'<h2>Sources</h2><ul>{sources}</ul>' if sources else "",
        },
    )


# ------------------------------------------------------------------ 必备三页 + 404

def _page_meta(site: dict, path: str, title: str, description: str) -> dict:
    return {
        "canonical": f'{site["base_url"]}{path}',
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }


def _webpage_graph(site: dict, path: str, title: str, description: str) -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": title,
        "description": description,
        "url": f'{site["base_url"]}{path}',
        "isPartOf": {"@type": "WebSite", "name": site["title"], "url": f'{site["base_url"]}/'},
    }


def build_about(site: dict, providers: list[dict], generated_at: str) -> str:
    path = "/about"
    title = f'About {site["title"]}'
    description = (
        f'{site["title"]} is an independent tracker of VPS prices published by hosting providers. '
        "Every number links back to the provider page it came from. Written and maintained by an independent developer."
    )
    meta = _page_meta(site, path, title, description)
    return render(
        template("about.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, path, title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "site_title": escape(site["title"]),
            "repo_url": escape(site["repo_url"]),
        },
    )


def build_privacy(site: dict, providers: list[dict], generated_at: str) -> str:
    path = "/privacy"
    title = f'Privacy Policy - {site["title"]}'
    description = (
        "What data this site does and does not handle: third-party advertising, affiliate links, "
        "the analytics that are actually installed, no accounts and no forms."
    )
    meta = _page_meta(site, path, title, description)
    # 隐私政策必须与"实际装了什么"一致：装了 GA4 就不能再写"没有任何统计"。
    if VERIFY.get("ga4"):
        analytics_sentence = (
            "<strong>One analytics script is installed.</strong> This site uses Google Analytics 4 "
            f"({escape(VERIFY['ga4'])}) to count visits and page views. It sets cookies and processes "
            "your IP address and request data under Google's privacy policy."
        )
        analytics_detail = (
            "<h2>Google Analytics 4</h2>"
            f"<p>The measurement ID in use is <code>{escape(VERIFY['ga4'])}</code>. It is loaded on every page. "
            "Google acts as a processor for this data; see "
            '<a href="https://policies.google.com/privacy" rel="noopener" target="_blank">policies.google.com/privacy</a>. '
            "You can block it with any content blocker or browser setting without losing access to the site.</p>"
        )
    else:
        analytics_sentence = (
            "<strong>No first-party analytics.</strong> No analytics or tracking script of our own is installed, "
            "and no first-party cookies are set."
        )
        analytics_detail = ""
    return render(
        template("privacy.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, path, title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "site_title": escape(site["title"]),
            "base_url": site["base_url"],
            "generated_date": generated_at[:10],
            "analytics_sentence": analytics_sentence,
            "analytics_detail": analytics_detail,
        },
    )


def build_contact(site: dict, providers: list[dict], generated_at: str) -> str:
    path = "/contact"
    title = f'Contact - {site["title"]}'
    description = "How to reach the site: email contact@vpsdealsradar.com for price corrections, provider suggestions and privacy questions."
    meta = _page_meta(site, path, title, description)
    return render(
        template("contact.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, path, title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "base_url": site["base_url"],
        },
    )


def build_404(site: dict, providers: list[dict], generated_at: str) -> str:
    title = f'404 - page not found - {site["title"]}'
    meta = _page_meta(site, "/404", title, "There is no page at that address.")
    meta["canonical"] = f'{site["base_url"]}/404'
    return render(
        template("404.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, []),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "base_url": site["base_url"],
        },
    )


# ------------------------------------------------------------------ 主流程

def main() -> int:
    global ASSET_V
    config = load_config()
    site_cfg = config["site"]
    payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))

    base_url = "https://" + site_cfg["domain"].rstrip("/")
    site = {
        "brand": site_cfg.get("brand", "vps-deals"),
        "title": site_cfg.get("title", "VPS Deals Radar"),
        "tagline": site_cfg.get("tagline", ""),
        "locale": site_cfg.get("locale", "en-US"),
        "domain": site_cfg["domain"],
        "base_url": base_url,
        "og_image": site_cfg.get("og_image", f"{base_url}/og.png"),
        "repo_url": site_cfg.get("repo", ""),
    }
    offers = payload["offers"]
    variants: dict[tuple, int] = {}
    offers, variants = collapse_offers(offers)
    providers = payload["providers"]
    by_name = {row["name"]: row for row in providers}
    generated_at = payload["generated_at"]

    SITE_DIR.mkdir(parents=True, exist_ok=True)
    (SITE_DIR / "provider").mkdir(exist_ok=True)
    (SITE_DIR / "deal").mkdir(exist_ok=True)
    (SITE_DIR / "assets").mkdir(exist_ok=True)
    (SITE_DIR / "guide").mkdir(exist_ok=True)
    (SITE_DIR / "downloads").mkdir(exist_ok=True)

    ASSET_V = re.sub(r"[^0-9A-Za-z]", "", generated_at) or "0"
    VERIFY["gsc"] = (site_cfg.get("gsc_verification") or "").strip()
    VERIFY["ga4"] = (site_cfg.get("ga4_measurement_id") or "").strip()
    if VERIFY["ga4"] and not re.fullmatch(r"G-[A-Z0-9]{4,}", VERIFY["ga4"]):
        raise SystemExit(f'ga4_measurement_id 看起来不是 GA4 衡量 ID：{VERIFY["ga4"]!r}（应形如 G-XXXXXXXXXX）')
    asset_paths = []
    if ASSET_DIR.exists():
        for asset in sorted(ASSET_DIR.iterdir()):
            if asset.is_file():
                (SITE_DIR / "assets" / asset.name).write_text(asset.read_text(encoding="utf-8"), encoding="utf-8")
                asset_paths.append(f"/assets/{asset.name}")

    # 社交分享大图（真 PNG，构建时用标准库生成；og:image 指向它，不再是一条坏链接）
    build_og_image(site, SITE_DIR / "og.png")
    asset_paths.append("/og.png")

    written = []
    for name, html in {
        "index.html": build_index(site, offers, providers, generated_at),
        "compare.html": build_compare(site, offers, providers, generated_at),
        "about.html": build_about(site, providers, generated_at),
        "privacy.html": build_privacy(site, providers, generated_at),
        "contact.html": build_contact(site, providers, generated_at),
        "404.html": build_404(site, providers, generated_at),
    }.items():
        (SITE_DIR / name).write_text(html, encoding="utf-8")
        written.append(name)

    grouped = group_offers(offers)
    for provider in providers:
        html = build_provider(site, provider, grouped.get(provider["name"], []), generated_at)
        path = SITE_DIR / "provider" / f"{slugify(provider['name'])}.html"
        path.write_text(html, encoding="utf-8")
        written.append(f"provider/{path.name}")

    for offer in offers:
        html = build_deal(site, offer, generated_at, variants.get((offer["provider"], offer["title"].lower()), 1))
        path = SITE_DIR / "deal" / f"{offer_slug(offer)}.html"
        path.write_text(html, encoding="utf-8")
        written.append(f"deal/{path.name}")

    # 可下载的比价表：三家里没有任何一家提供这种文件，这是这个词最集中的缺口。
    csv_body, csv_rows = build_unit_price_csv(offers)
    (SITE_DIR / "downloads" / "unit-price.csv").write_text(csv_body, encoding="utf-8")

    # 指南栏：每篇只补一个缺口，内容由 data/guides.json 提供，渲染是确定性的。
    guides = json.loads(GUIDES_PATH.read_text(encoding="utf-8")) if GUIDES_PATH.exists() else []
    # 清掉已经不存在的指南页，否则旧日期的页面会一直留在线上的目录里变成孤儿页。
    # 只删"带日期后缀的自动页"（csv-YYYY-MM-DD-n / unitprice-... / steps-...），手写页不碰。
    keep = {f'{guide["slug"]}.html' for guide in guides}
    for stale in sorted((SITE_DIR / "guide").glob("*.html")):
        if stale.name in keep:
            continue
        if re.match(r"^(csv|unitprice|steps)-\d{4}-\d{2}-\d{2}-\d+\.html$", stale.name):
            stale.unlink()
            written.append(f"removed stale guide/{stale.name}")
    (SITE_DIR / "guide.html").write_text(
        build_guide_index(site, guides, offers, providers, generated_at), encoding="utf-8"
    )
    written.append("guide.html")
    for guide in guides:
        html = build_guide(site, guide, offers, providers, generated_at)
        path = SITE_DIR / "guide" / f'{guide["slug"]}.html'
        path.write_text(html, encoding="utf-8")
        written.append(f"guide/{path.name}")

    urls = [home_url(site), compare_url(site)]
    urls += [f"{base_url}/about", f"{base_url}/privacy", f"{base_url}/contact"]
    urls += [provider_page(site, row["name"]) for row in providers]
    urls += [deal_page(site, offer) for offer in offers]
    urls += [guides_url(site)]
    urls += [guide_page(site, guide) for guide in guides]
    # 指南页用各自的发布日期做 lastmod（自动页有 published），其余用本次构建时间。
    lastmod_for = {guide_page(site, guide): guide.get("published", generated_at) for guide in guides}
    sitemap = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in urls:
        lastmod = lastmod_for.get(url, generated_at)
        sitemap.append(f"  <url><loc>{escape(url)}</loc><lastmod>{escape(lastmod)}</lastmod></url>")
    sitemap.append("</urlset>")
    (SITE_DIR / "sitemap.xml").write_text("\n".join(sitemap) + "\n", encoding="utf-8")
    (SITE_DIR / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\n\nSitemap: {base_url}/sitemap.xml\n", encoding="utf-8"
    )
    # 合法路径白名单：由这次构建实际写出的页面生成，交给 _worker.js 判 404。
    # 不写死在这里，就不会出现"加了页面却忘了改 404 逻辑"。
    valid_paths = ["/", "/compare", "/about", "/privacy", "/contact", "/sitemap.xml", "/robots.txt", "/guide"]
    valid_paths += asset_paths
    valid_paths.append("/downloads/unit-price.csv")
    valid_paths += [f"/provider/{slugify(row['name'])}" for row in providers]
    valid_paths += [f"/deal/{offer_slug(offer)}" for offer in offers]
    valid_paths += [f'/guide/{guide["slug"]}' for guide in guides]
    (SITE_DIR / "_worker.js").write_text(
        WORKER_TEMPLATE.replace("__CANONICAL_HOST__", site_cfg["domain"]).replace(
            "__VALID_PATHS__", json.dumps(valid_paths)
        ),
        encoding="utf-8",
    )

    print(
        f"wrote {len(written)} pages + sitemap.xml({len(urls)} urls) + robots.txt + "
        f"_worker.js(301 canonical host, real 404, {len(valid_paths)} allowed paths)"
    )
    print(f"data snapshot {generated_at} | offers {len(offers)} | providers {len(by_name)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
