# ILANG
# TYPE:module ROLE:builder PROJECT:vps-deals
# ::RULE{配置与文案参数来自 .ilang/site.ilang 和 data/offers.json⇒不许在代码里另写一份}
# ::RULE{没有 price 的优惠⇒页面照常列 但不写 price 也不写 priceCurrency 进结构化数据}
# ::RULE{每页必须有 canonical 和 JSON-LD⇒sitemap.xml 和 robots.txt 由本文件生成 不手写}
# ::RULE{标题和描述由数据生成⇒带厂商名 价格 和当前月份 不许所有页共用一句模板}
# ::BOUNDARY{never:编价格 编有效期 编评分|scope:file}
"""读 data/offers.json -> 渲染静态站到 site/（含 JSON-LD、canonical、sitemap）

零依赖：只用 Python 标准库。
用法：python build.py
"""

from __future__ import annotations

import json
import re
import struct
import zlib
from datetime import datetime, timezone
from html import escape
from pathlib import Path

from scraper import load_config
from guides import frequently_asked
import chart_assets

ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "data" / "offers.json"
GUIDES_PATH = ROOT / "data" / "guides.json"
TEMPLATE_DIR = ROOT / "templates"
ASSET_DIR = TEMPLATE_DIR / "assets"
SITE_DIR = ROOT / "site"

SYMBOLS = {"USD": "$", "EUR": "€", "GBP": "£"}
MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# Cloudflare Pages 高级模式脚本：放在输出目录里，全量接管请求。
# ::_redirects 不支持域名级跳转（官方文档 Domain-level redirects ❌），
# ::所以 *.pages.dev（含预览哈希地址）这类非规范主机名必须在这里 301 到主域名，
# ::避免同一个站有两个地址并存、把权重分散掉。主域名请求照常走静态资源。
WORKER_TEMPLATE = """// ILANG
// TYPE:worker ROLE:canonical-host-and-real-404
// ::RULE{non-canonical hosts get a 301 to the canonical domain; never leave two live addresses}
// ::RULE{paths outside the allow-list get a real 404; never let Pages fall back to the homepage}
// ::RULE{the allow-list is generated by build.py, so adding a page needs no edit here}
// ::BOUNDARY{never:render content from this file|scope:file}
const CANONICAL_HOST = "__CANONICAL_HOST__";
const VALID_PATHS = new Set(__VALID_PATHS__);

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.hostname !== CANONICAL_HOST) {
      return Response.redirect(new URL(url.pathname + url.search, `https://${CANONICAL_HOST}`).toString(), 301);
    }

    const path = url.pathname.replace(/\\/+$/, "") || "/";

    // Legacy /xxx.html addresses from earlier deploys: permanent redirect to the clean path
    if (path.endsWith(".html")) {
      const bare = path === "/index.html" ? "/" : path.slice(0, -5);
      if (VALID_PATHS.has(bare)) {
        return Response.redirect(new URL(bare + url.search, `https://${CANONICAL_HOST}`).toString(), 308);
      }
    }

    if (VALID_PATHS.has(path)) {
      return env.ASSETS.fetch(request);
    }

    // Cloudflare Pages answers unmatched paths with the homepage and a 200.
    // Turn that into a real 404: search engines and reviewers should not see a valid page
    // at an address that does not exist.
    const notFound = await env.ASSETS.fetch(new URL("/404.html", url));
    return new Response(notFound.body, {
      status: 404,
      headers: {
        "content-type": "text/html; charset=utf-8",
        "cache-control": "no-store",
        "x-robots-tag": "noindex",
      },
    });
  },
};
"""


# ------------------------------------------------------------------ 小工具

def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "item"


# Google 对 Product 的必填字段是 name + offers，对 Offer 要 price。
# 发一个"没有 offers 的 Product"或"没有 price 的 Offer"，Search Console 里就是硬错误
# （2026-10-02 的 GSC 报的就是这一类）。构建时先自查一遍，宁可构建失败也不发出去。
def audit_structured_data(site_dir: Path) -> list[str]:
    """把 site/ 里每个页面上的 JSON-LD 块过一遍，返回发现的问题（空列表=通过）。"""
    problems: list[str] = []

    def walk(node, where: str) -> None:
        if isinstance(node, list):
            for item in node:
                walk(item, where)
            return
        if not isinstance(node, dict):
            return
        kind = node.get("@type")
        if kind == "Product":
            offers = node.get("offers")
            if not offers:
                problems.append(f"{where}: Product 没有 offers（Google 必填字段）")
            else:
                walk(offers, where)
        elif kind == "Offer" and node.get("price") is None:
            problems.append(f"{where}: Offer 没有 price（Google 必填字段）")
        elif kind == "AggregateOffer" and node.get("lowPrice") is None:
            problems.append(f"{where}: AggregateOffer 没有 lowPrice（Google 必填字段）")
        for value in node.values():
            if isinstance(value, (dict, list)):
                walk(value, where)

    for page_path in sorted(site_dir.rglob("*.html")):
        page_text = page_path.read_text(encoding="utf-8")
        for match in re.finditer(r'<script type="application/ld\+json">(.*?)</script>', page_text, re.S):
            try:
                payload = json.loads(match.group(1))
            except ValueError as exc:
                problems.append(f"{page_path.name}: JSON-LD 不是合法 JSON（{exc}）")
                continue
            walk(payload, page_path.name)
    return problems


# Cloudflare Pages 会把 /x.html 308 跳到 /x，所以 canonical 和 sitemap 一律用干净 URL，
# 文件本身仍然写成 .html —— 让被索引的地址就是最终地址，避免 canonical 指向一个跳转。
def home_url(site: dict) -> str:
    return f'{site["base_url"]}/'


def compare_url(site: dict) -> str:
    return f'{site["base_url"]}/compare'


def provider_page(site: dict, name: str) -> str:
    return f'{site["base_url"]}/provider/{slugify(name)}'


def deal_page(site: dict, offer: dict) -> str:
    return f'{site["base_url"]}/deal/{offer_slug(offer)}'


def render(template: str, values: dict[str, str]) -> str:
    def replace(match: re.Match) -> str:
        key = match.group(1).strip()
        return values.get(key, "")

    return re.sub(r"\{\{\s*([a-zA-Z0-9_]+)\s*\}\}", replace, template)


def template(name: str) -> str:
    html = (TEMPLATE_DIR / name).read_text(encoding="utf-8")
    # 样式统一收在 assets/style.css 一份；模板里若有历史内联 <style> 一律剥掉，
    # 否则内联样式会盖掉新设计（同权重下后出现的胜出）。
    return re.sub(r"\s*<style>.*?</style>", "", html, flags=re.S)


# 自动页的正文是 guides.py 生成那一刻写死进 data/guides.json 的，里面凡是**全站口径**的
# 数字（"25 个套餐"、"20 of 25 tracked plans"）都跟着那一刻冻住了；而同一页上的 FAQ、
# 页脚那句 "prices last read from the providers" 和 /downloads/unit-price.csv 每次构建
# 重算。两边一旦不同步，同一页就说两套话：2026-10-05 线上 /guide/csv-2026-09-24-1 的正文
# 写 "20 of 25 tracked plans"，同页 FAQ 写 "25 of 25 priced plans"，CSV 也是 25 行。
# 所以这些数字在 guides.py 里只留占位符，构建时用当天的抓取结果填。按行数算的
# （这页排了几行）不在此列——那本来就是这一页自己的事实，不会随时间漂。
def live_counts(offers: list[dict]) -> dict[str, int]:
    priced = [o for o in offers if o.get("price") is not None]
    return {
        "priced_count": len(priced),
        "with_ram_count": sum(1 for o in priced if o.get("ram_gb")),
    }


def expand_live_tokens(text: str, offers: list[dict]) -> str:
    """把全站口径的占位符换成今天抓到的数字。

    换不掉的占位符直接报错，绝不发出去：render() 对没见过的 key 是替换成空串的，
    漏一个就会印出 "The full -plan table" 这种缺数字的句子。
    """
    if "{{" not in text:
        return text
    values = {key: str(value) for key, value in live_counts(offers).items()}
    expanded = re.sub(
        r"\{\{\s*([a-z_]+)\s*\}\}",
        lambda match: values.get(match.group(1), match.group(0)),
        text,
    )
    leftover = sorted(set(re.findall(r"\{\{\s*([a-z_]+)\s*\}\}", expanded)))
    if leftover:
        raise SystemExit("unknown live token(s) in guide text: " + ", ".join(leftover))
    return expanded


def money(price: float | None, currency: str) -> str:
    if price is None:
        return ""
    symbol = SYMBOLS.get(currency, "")
    amount = f"{price:.2f}".rstrip("0").rstrip(".") if price % 1 else f"{price:.0f}"
    return f"{symbol}{amount} {currency}" if not symbol else f"{symbol}{amount}"


def jsonld(payload: dict | list) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def iso_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------- 社交分享大图
# 社交平台不接受 SVG，所以这张 OG 图在构建时用纯标准库自己写成 PNG：
# 没有 Pillow、没有外部服务，画的还是那套像素字和那只猫。
PIXEL_FONT = {
    "V": ["#...#", "#...#", "#...#", "#...#", "#...#", ".#.#.", "..#.."],
    "P": ["####.", "#...#", "#...#", "####.", "#....", "#....", "#...."],
    "S": [".####", "#....", "#....", ".###.", "....#", "....#", "####."],
    "D": ["###..", "#..#.", "#...#", "#...#", "#...#", "#..#.", "###.."],
    "E": ["#####", "#....", "#....", "####.", "#....", "#....", "#####"],
    "A": ["..#..", ".#.#.", "#...#", "#####", "#...#", "#...#", "#...#"],
    "L": ["#....", "#....", "#....", "#....", "#....", "#....", "#####"],
    "R": ["####.", "#...#", "#...#", "####.", "#.#..", "#..#.", "#...#"],
    " ": [".....", ".....", ".....", ".....", ".....", ".....", "....."],
}
CAT_ART = [
    "....##......##....",
    "...####....####...",
    "...####....####...",
    "..##############..",
    "..##############..",
    "..##..######..##..",
    "..##..######..##..",
    "..##############..",
    "..####..####..##..",
    "..##############..",
    "...############...",
    "....##########....",
    "...############...",
    "..##############..",
    "..##############..",
    "...############...",
]


def _png_bytes(width: int, height: int, pixels: list) -> bytes:
    """极简 PNG 编码器（8 位 RGB、无滤波），只依赖 zlib 与 struct。"""
    raw = bytearray()
    for row in pixels:
        raw.append(0)
        for rgb in row:
            raw.extend(rgb)
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


def build_og_image(site: dict, path: Path) -> None:
    W, H = 1200, 630
    bg, panel, accent, fur, ink, line = (10, 13, 19), (18, 25, 38), (246, 130, 31), (238, 242, 248), (20, 28, 40), (33, 44, 61)
    pixels = [[bg for _ in range(W)] for _ in range(H)]

    def fill(x0, y0, w, h, colour):
        for y in range(max(0, y0), min(H, y0 + h)):
            row = pixels[y]
            for x in range(max(0, x0), min(W, x0 + w)):
                row[x] = colour

    # 轻微渐变的底 + 左侧强调色竖条
    for y in range(H):
        shade = 14 + int(10 * (1 - y / H))
        row = pixels[y]
        for x in range(W):
            row[x] = (bg[0] + shade // 3, bg[1] + shade // 2, bg[2] + shade)
    fill(0, 0, 14, H, accent)

    # 像素字：VPS DEALS RADAR（放在猫下面，缩到不会溢出右边缘）
    text = "VPS DEALS RADAR"
    scale, gap = 8, 3
    gw, gh = 5 * scale, 7 * scale
    total = len(text) * gw + (len(text) - 1) * gap
    x = (W - total) // 2
    y = 372
    for ch in text:
        glyph = PIXEL_FONT.get(ch, PIXEL_FONT[" "])
        for gy, row in enumerate(glyph):
            for gx, dot in enumerate(row):
                if dot == "#":
                    fill(x + gx * scale, y + gy * scale, scale, scale, fur)
        x += gw + gap

    # 那只猫（16x16 像素画，放大 11 倍，放在上半部）
    cat_scale = 11
    cat_w, cat_h = 16 * cat_scale, 16 * cat_scale
    cx, cy = (W - cat_w) // 2, 118
    for gy, row in enumerate(CAT_ART):
        for gx, dot in enumerate(row):
            if dot == "#":
                fill(cx + gx * cat_scale, cy + gy * cat_scale, cat_scale, cat_scale, fur)
    # 耳朵内侧 + 眼睛 + 鼻子 + 领圈（与页面上那只同一套配色）
    fill(cx + 3 * cat_scale, cy + 1 * cat_scale, cat_scale, 2 * cat_scale, accent)
    fill(cx + 12 * cat_scale, cy + 1 * cat_scale, cat_scale, 2 * cat_scale, accent)
    fill(cx + 3 * cat_scale, cy + 5 * cat_scale, 2 * cat_scale, 2 * cat_scale, ink)
    fill(cx + 9 * cat_scale, cy + 5 * cat_scale, 2 * cat_scale, 2 * cat_scale, ink)
    fill(cx + 7 * cat_scale, cy + 8 * cat_scale, 2 * cat_scale, cat_scale, accent)
    fill(cx, cy + 12 * cat_scale, cat_w, cat_scale, accent)

    # 底部一条分隔线
    fill(0, H - 96, W, 2, line)
    path.write_bytes(_png_bytes(W, H, pixels))


# 静态资产的缓存版本号：每次构建都不同，访客不会拿到上一版的 css/js。
# 在 main() 里按数据快照时间赋值。
ASSET_V = "0"

# 站点验证与统计：来自 .ilang/site.ilang 的 @SITE 状态；留空即不注入。
VERIFY: dict[str, str] = {"gsc": "", "ga4": ""}

# 本次构建的厂商清单（main 里赋值）。页脚要据此决定"有没有联盟链接"的自述，
# 用模块变量是为了不去改十几处 footer_block 调用点。
PROVIDERS_CTX: list[dict] = []


# ------------------------------------------------------------------ 数据整理

def group_offers(offers: list[dict]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for offer in offers:
        grouped.setdefault(offer["provider"], []).append(offer)
    for rows in grouped.values():
        rows.sort(key=lambda row: (row.get("price") is None, row.get("price") or 0))
    return grouped


def collapse_offers(offers: list[dict]) -> tuple[list[dict], dict[tuple, int]]:
    """同一家厂商同一个套餐名可能公布多个价格（原价/促销价）。

    塌缩成一条（保留更低那个），并记录公布了几个价格，供页面如实说明。
    不合并的话 slug 会撞车：一个页面被另一个覆盖，sitemap 还会出现重复 URL。
    """
    best: dict[tuple, dict] = {}
    variants: dict[tuple, int] = {}
    for offer in offers:
        key = (offer["provider"], offer["title"].lower())
        variants[key] = variants.get(key, 0) + 1
        current = best.get(key)
        if current is None:
            best[key] = dict(offer)
            continue
        if offer.get("price") is not None and (
            current.get("price") is None or offer["price"] < current["price"]
        ):
            current["price"] = offer["price"]
            current["currency"] = offer.get("currency", current.get("currency"))
        if offer.get("valid_until") and not current.get("valid_until"):
            current["valid_until"] = offer["valid_until"]
    return list(best.values()), variants


def offer_slug(offer: dict) -> str:
    return slugify(f"{offer['provider']}-{offer['title']}")


def affiliate_for(offer: dict, providers: dict[str, dict]) -> str:
    """联盟链接优先；site.ilang 里留空就用抓到的裸链。"""
    provider = providers.get(offer["provider"], {})
    return provider.get("affiliate_url") or offer["offer_url"]


# ------------------------------------------------------------------ 头部与骨架

def head_block(meta: dict, extra_jsonld: list[dict] | None = None) -> str:
    links = [
        f'<link rel="canonical" href="{escape(meta["canonical"])}">',
        f'<link rel="alternate" hreflang="{escape(meta["locale"])}" href="{escape(meta["canonical"])}">',
        f'<link rel="alternate" hreflang="x-default" href="{escape(meta["canonical"])}">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<meta name="robots" content="index,follow,max-image-preview:large">',
        f'<link rel="stylesheet" href="/assets/style.css?v={ASSET_V}">',
        f'<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg?v={ASSET_V}">',
        f'<script src="/assets/pets.js?v={ASSET_V}" defer></script>',
    ]
    # 站点验证与统计只在配置里填了值时才出现；留空时页面里干干净净，隐私政策也照实说没有。
    if VERIFY.get("gsc"):
        links.append(f'<meta name="google-site-verification" content="{escape(VERIFY["gsc"])}">')
    if VERIFY.get("ga4"):
        gid = escape(VERIFY["ga4"])
        links.append(f'<script async src="https://www.googletagmanager.com/gtag/js?id={gid}"></script>')
        links.append(
            "<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}"
            f"gtag('js',new Date());gtag('config','{gid}');</script>"
        )
    social = [
        f'<meta property="og:type" content="{escape(meta["og_type"])}">',
        f'<meta property="og:title" content="{escape(meta["title"])}">',
        f'<meta property="og:description" content="{escape(meta["description"])}">',
        f'<meta property="og:url" content="{escape(meta["canonical"])}">',
        f'<meta property="og:site_name" content="{escape(meta["brand"])}">',
        f'<meta property="og:image" content="{escape(meta["og_image"])}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{escape(meta["title"])}">',
        f'<meta name="twitter:description" content="{escape(meta["description"])}">',
        f'<meta name="twitter:image" content="{escape(meta["og_image"])}">',
        f'<meta name="description" content="{escape(meta["description"])}">',
    ]
    blocks = [f'<script type="application/ld+json">{jsonld(item)}</script>' for item in (extra_jsonld or [])]
    return "\n  ".join(links + social + blocks)


def nav_block(site: dict, providers: list[dict]) -> str:
    """顶部导航：把指南栏和对比页也放进站点级导航。

    之前只列了首页、对比页和厂商页，14 个指南页在页面上彼此不指路（只能靠 sitemap），
    指南入口只藏在页脚。少一条链接就少一条被抓到的路径。
    """
    links = [f'<a href="{escape(home_url(site))}">Home</a>']
    links.append(f'<a href="{escape(compare_url(site))}">Compare all</a>')
    links.append(f'<a href="{escape(guides_url(site))}">Guides</a>')
    links.append(f'<a href="{escape(site["base_url"])}/downloads/unit-price.csv">Price table (CSV)</a>')
    for provider in providers:
        links.append(
            f'<a href="{escape(provider_page(site, provider["name"]))}">{escape(provider["name"])}</a>'
        )
    return " · ".join(links)


def affiliate_live(providers: list[dict]) -> bool:
    """真的有联盟链接才算"有"。空着的时候不许在页脚或隐私政策里声称有。"""
    return any((row.get("affiliate_url") or "").strip() for row in providers)


def footer_block(site: dict, generated_at: str, providers: list[dict] | None = None) -> str:
    nav_links = " · ".join(
        [
            f'<a href="{escape(site["base_url"])}/about">About</a>',
            f'<a href="{escape(site["base_url"])}/methodology">Methodology</a>',
            f'<a href="{escape(site["base_url"])}/privacy">Privacy Policy</a>',
            f'<a href="{escape(site["base_url"])}/contact">Contact</a>',
            f'<a href="{escape(site["base_url"])}/sitemap.xml">Sitemap</a>',
        ]
    )
    # 资助方式的自述随事实变：没接联盟就说没接，别写将来时当现在时。
    if affiliate_live(providers if providers is not None else PROVIDERS_CTX):
        money = (
            '<p class="muted"><strong>Affiliate links:</strong> some outbound links to providers are affiliate '
            'links.</p>'
            '<p class="muted"><strong>Commission:</strong> if you sign up through one of those links, this site '
            'may earn a commission at no extra cost to you.</p>'
        )
    else:
        money = (
            '<p class="muted"><strong>Affiliate links:</strong> none active at present — outbound provider links '
            'carry no tracking parameter, so no commission is earned from them.</p>'
            '<p class="muted"><strong>Advertising:</strong> none shown — no ad network script runs on these pages.</p>'
        )
    return (
        f'<p class="muted">Prices are read from each provider\'s own public page on {escape(generated_at)} '
        "and can change without notice — always confirm on the provider site before buying.</p>"
        '<p class="muted">Independent listings. No invented prices: a plan without a published price shows no price.</p>'
        + money
        + f'<p class="muted">{escape(site["brand"])} · {nav_links}</p>'
        # 像素小动物的挂载点：纯装饰，画布由 assets/pets.js 生成。
        # 放在页脚里是因为页脚每页都有；它是 position:fixed，不影响版式。
        '<div class="critter" aria-hidden="true"></div>'
    )


# ------------------------------------------------------------------ 渲染各页

def offer_rows(offers: list[dict], site: dict, providers: dict[str, dict], with_provider: bool) -> str:
    rows = []
    for offer in offers:
        price = money(offer.get("price"), offer.get("currency", "USD"))
        price_cell = price if price else '<span class="muted">not published</span>'
        provider_cell = (
            f'<a href="{escape(provider_page(site, offer["provider"]))}">{escape(offer["provider"])}</a>'
            if with_provider
            else ""
        )
        detail = deal_page(site, offer)
        target = affiliate_for(offer, providers)
        rows.append(
            "<tr>"
            f"<td>{provider_cell}</td>"
            f'<td><a href="{escape(detail)}">{escape(offer["title"])}</a></td>'
            f'<td class="price">{price_cell}</td>'
            f'<td><a class="btn" rel="nofollow sponsored noopener" target="_blank" href="{escape(target)}">View on provider</a></td>'
            "</tr>"
        )
    return "\n".join(rows)


def build_index(site: dict, offers: list[dict], providers: list[dict], generated_at: str) -> str:
    grouped = group_offers(offers)
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    priced = [o for o in offers if o.get("price")]
    cheapest = min(priced, key=lambda o: o["price"]) if priced else None
    title = f"{site['title']} — {len(offers)} live VPS deals tracked ({month} {datetime.now(timezone.utc).year})"
    description = (
        f"{len(offers)} VPS plans tracked across {len(grouped)} providers, prices read straight from each "
        f"provider's public page. Updated {generated_at}."
    )
    if cheapest:
        description += f" Cheapest tracked plan: {cheapest['provider']} {cheapest['title']} at {money(cheapest['price'], cheapest.get('currency','USD'))}."

    cards = []
    for provider in providers:
        rows = grouped.get(provider["name"], [])
        if not rows:
            note = provider.get("note") or "no published price found on the source page"
            cards.append(
                f'<div class="card"><h3>{escape(provider["name"])}</h3>'
                f'<p class="muted">Tracked, but {escape(note)}.</p>'
                f'<p><a href="{escape(provider["homepage"])}" rel="nofollow noopener" target="_blank">Official site</a></p></div>'
            )
            continue
        lowest = rows[0]
        cards.append(
            f'<div class="card"><h3><a href="{escape(provider_page(site, provider["name"]))}">'
            f'{escape(provider["name"])}</a></h3>'
            f'<p class="price big">{escape(money(lowest.get("price"), lowest.get("currency","USD")))}</p>'
            f'<p class="muted">from {escape(lowest["title"])} · {len(rows)} plans tracked</p></div>'
        )

    item_list = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": title,
        "itemListElement": [
            {"@type": "ListItem", "position": index + 1,
             "url": deal_page(site, offer), "name": f'{offer["provider"]} {offer["title"]}'}
            for index, offer in enumerate(offers[:50])
        ],
    }
    website = {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": site["title"],
        "url": home_url(site),
        "description": description,
    }
    meta = {
        "canonical": home_url(site),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }
    # 第一屏先给答案：最便宜的一档、每 GB 最便宜的一档，都是抓到的数字现算的。
    with_ram = [o for o in priced if o.get("ram_gb")]
    answer_bits = []
    if cheapest:
        answer_bits.append(
            f"Lowest published monthly price right now: {money(cheapest['price'], cheapest.get('currency', 'USD'))} "
            f"({cheapest['provider']} {cheapest['title']})."
        )
    if with_ram:
        best = min(with_ram, key=lambda o: o["price"] / o["ram_gb"])
        answer_bits.append(
            f"Lowest published price per GB of RAM: {best['price'] / best['ram_gb']:.4f} "
            f"{best.get('currency', '')} per GB ({best['provider']} {best['title']}, "
            f"{money(best['price'], best.get('currency', 'USD'))} / {best['ram_gb']} GB)."
        )
    answer_bits.append(
        f"{len(priced)} of {len(offers)} tracked plans publish a price; every row links to the provider page it "
        f"was read from."
    )
    return render(
        template("index.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [website, item_list]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "tagline": escape(site["tagline"]),
            "answer": escape(" ".join(answer_bits)),
            "chart": _chart_html(
                "per-gb-cheapest.svg",
                alt="Monthly price per GB of RAM for every tracked plan that publishes both numbers",
            ),
            "generated_at": generated_at,
            "cards": "\n".join(cards),
            "rows": offer_rows(offers[:60], site, {}, True),
            "offer_count": str(len(offers)),
            "provider_count": str(len(grouped)),
        },
    )


def build_provider(site: dict, provider: dict, offers: list[dict], generated_at: str) -> str:
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    name = provider["name"]
    priced = [o for o in offers if o.get("price")]
    low = min((o["price"] for o in priced), default=None)
    high = max((o["price"] for o in priced), default=None)
    currency = offers[0].get("currency", provider.get("currency", "USD")) if offers else provider.get("currency", "USD")

    title = f"{name} VPS prices ({month} {datetime.now(timezone.utc).year}) — {len(offers)} plans tracked"
    description = (
        f"{name} VPS plans with prices read from the provider's public page on {generated_at}. "
        + (f"{len(priced)} of {len(offers)} plans publish a price; from {money(low, currency)}." if priced
           else "No price is published in machine-readable form on that page, so this page lists plan names only.")
    )
    # 结构化数据只声明"这页是什么 + 列了哪些套餐"，不声明"我们在卖"。
    # 2026-10-02 改：原来这里发 Product + AggregateOffer。两个问题：
    #   1) 抓不到价格的厂商（DigitalOcean / Hetzner）会发出**没有 offers 的 Product**，
    #      Google 的必填字段就是 name + offers，于是 Search Console 里是实打实的错误；
    #   2) 有价格的厂商会被当成"商家信息"（merchant listing）来校验，而商家信息要求
    #      priceValidUntil / 退货政策 / 运费政策——我们是比价站，这三样一概没有。
    #      为了消警告去编一个 priceValidUntil 是编有效期，仓库的 BOUNDARY 不允许。
    # 所以不再发 Product/Offer，改成 ItemList：我们确实在做的、也确实为真的那件事。
    graphs: list[dict] = [
        {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": title,
            "url": provider_page(site, name),
            "description": description,
        }
    ]
    if priced:
        graphs.append(
            {
                "@context": "https://schema.org",
                "@type": "ItemList",
                "name": f"{name} VPS plans tracked with a published price",
                "itemListOrder": "https://schema.org/ItemListOrderAscending",
                "numberOfItems": len(priced),
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": index + 1,
                        "name": f"{name} {offer['title']}",
                        "url": deal_page(site, offer),
                        "description": f"Published price {money(offer['price'], offer.get('currency', currency))}",
                    }
                    for index, offer in enumerate(sorted(priced, key=lambda row: row["price"]))
                ],
            }
        )
    graphs.append(
        {
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": site["title"], "item": home_url(site)},
                {"@type": "ListItem", "position": 2, "name": name, "item": provider_page(site, name)},
            ],
        }
    )
    # 两段都由已抓到的数字算出；没有数据就如实说明原因，不填充套话。
    if offers:
        basis_rows = [
            f"<tr><th>Plans readable on the source page</th><td>{len(offers)}</td></tr>",
            f"<tr><th>Of those, publishing a price</th><td>{len(priced)}</td></tr>",
        ]
        with_ram = [o for o in priced if o.get("ram_gb")]
        basis_rows.append(
            f"<tr><th>Publishing a RAM figure beside the price</th><td>{len(with_ram)}</td></tr>")
        basis_rows.append(
            f"<tr><th>Read from</th><td><a href=\"{escape(provider['deals_url'])}\" rel=\"nofollow noopener\" "
            f"target=\"_blank\">{escape(provider['deals_url'])}</a></td></tr>")
        basis_rows.append(f"<tr><th>Read at (UTC)</th><td>{escape(generated_at)}</td></tr>")
        basis = ('<div class="table-shell"><table><tbody>' + "".join(basis_rows) + "</tbody></table></div>")
    else:
        reason = escape(provider.get("note") or "no readable price was found on the source page")
        basis = (
            f'<p>Nothing from {escape(name)} appears in the price table at the moment. The reason recorded by '
            f"the crawler for this run is: <em>{reason}</em>.</p>"
            f'<p class="muted">That is not a judgement about the provider — it means this site could not read a '
            f"published price from "
            f'<a href="{escape(provider["deals_url"])}" rel="nofollow noopener" target="_blank">their page</a> '
            f"on {escape(generated_at)} (UTC), and it does not publish a price it cannot read.</p>"
        )

    ranked = sorted([o for o in priced if o.get("ram_gb")], key=lambda o: o["price"] / o["ram_gb"])
    if ranked:
        per_rows = "".join(
            "<tr>"
            f'<td>{i + 1}</td>'
            f'<td><a href="{escape(deal_page(site, o))}">{escape(o["title"])}</a></td>'
            f'<td class="price">{escape(money(o["price"], o.get("currency", "USD")))}</td>'
            f'<td>{o["ram_gb"]} GB</td>'
            f'<td class="price">{o["price"] / o["ram_gb"]:.4f} {escape(o.get("currency", ""))}</td>'
            "</tr>"
            for i, o in enumerate(ranked)
        )
        per_gb = (
            _chart_html(
                f"per-gb-{slugify(name)}.svg",
                f"monthly-vs-ram-{slugify(name)}.svg",
                alt=f'Monthly price per GB of RAM at {name}, computed from published prices',
            )
            + '<div class="table-shell"><table><thead><tr><th>#</th><th>Plan</th><th>Published price</th>'
            '<th>RAM</th><th>Per GB</th></tr></thead><tbody>' + per_rows + "</tbody></table></div>"
            + f'<p class="muted">{len(ranked)} of {len(priced)} priced plans publish the RAM figure this '
              f'division needs. The rest are left out rather than estimated.</p>'
        )
    else:
        per_gb = (
            '<p class="muted">A price-per-GB figure needs two published numbers: the monthly price and the RAM '
            'figure beside it. No plan from this provider currently publishes both, so no per-unit figure is '
            'shown. See the '
            f'<a href="{escape(site["base_url"])}/methodology">methodology page</a> for how that decision is made.</p>'
        )

    meta = {
        "canonical": provider_page(site, name),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }
    return render(
        template("provider.html"),
        {
            "lang": site["locale"],
            "brand": escape(site["brand"]),
            "head": head_block(meta, graphs),
            "nav": nav_block(site, [provider]),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "provider": escape(name),
            "homepage": escape(provider["homepage"]),
            "source_url": escape(provider["deals_url"]),
            "generated_at": generated_at,
            "rows": offer_rows(offers, site, {}, False) or '<tr><td colspan="4" class="muted">No plan with a published price was found on the source page.</td></tr>',
            "low": money(low, currency) if low else "",
            "high": money(high, currency) if high else "",
            "offer_count": str(len(offers)),
            "priced_count": str(len(priced)),
            "note": escape(provider.get("note") or ""),
            "basis": basis,
            "per_gb": per_gb,
            "base_url": escape(site["base_url"]),
        },
    )


def build_deal(site: dict, offer: dict, generated_at: str, variants: int = 1,
               provider_offers: list[dict] | None = None) -> str:
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    currency = offer.get("currency", "USD")
    price_text = money(offer.get("price"), currency)
    title = f'{offer["provider"]} {offer["title"]}' + (f' — {price_text} ({month})' if price_text else f' ({month})')
    description = (
        f'{offer["provider"]} {offer["title"]}'
        + (f' listed at {price_text}' if price_text else ' (no published price found)')
        + f'. Read from {offer["source_url"]} on {offer["fetched_at"]}.'
    )
    # 这一页记录"我们从厂商页面上读到的那个价格"，不是"我们在卖这个东西"。
    # 原来发的是一个裸 Offer（不在 Product 里）：Google 不认这种形状，而且它把页面
    # 拉进商家信息的校验口径，缺 priceValidUntil 就报错。我们抓不到有效期就不写有效期
    # （数据集里 0 条有 valid_until），所以不再发 Offer，改成 WebPage + 这一档的规格。
    schema: dict = {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": f'{offer["provider"]} {offer["title"]}',
        "url": deal_page(site, offer),
        "description": description,
    }
    breadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": site["title"], "item": home_url(site)},
            {"@type": "ListItem", "position": 2, "name": offer["provider"],
             "item": provider_page(site, offer["provider"])},
            {"@type": "ListItem", "position": 3, "name": offer["title"], "item": deal_page(site, offer)},
        ],
    }
    meta = {
        "canonical": deal_page(site, offer),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "product",
        "og_image": site["og_image"],
    }
    # 三张表全部由已抓到的数字算出；缺输入就如实写"未公布"，不补不估。
    def _row(label: str, value: str) -> str:
        return f"<tr><th>{escape(label)}</th><td>{value}</td></tr>"

    price_value = offer.get("price")
    ram = offer.get("ram_gb")
    vcpu = offer.get("vcpu")
    disk = offer.get("disk_gb")
    currency_code = escape(currency)

    specs_rows = []
    specs_rows.append(_row("Published price",
                           escape(price_text) if price_text else
                           '<span class="muted">no price published on the source page</span>'))
    specs_rows.append(_row("Memory (RAM)",
                           f"{ram} GB" if ram else '<span class="muted">not published next to the price</span>'))
    specs_rows.append(_row("vCPU",
                           str(vcpu) if vcpu else '<span class="muted">not published next to the price</span>'))
    specs_rows.append(_row("Disk",
                           f"{disk} GB" if disk else '<span class="muted">not published next to the price</span>'))
    specs_rows.append(_row("Currency", currency_code))
    specs_rows.append(_row("Read from",
                           f'<a href="{escape(offer["source_url"])}" rel="nofollow noopener" target="_blank">'
                           f'{escape(offer["source_url"])}</a>'))
    specs_rows.append(_row("Read at (UTC)", escape(offer["fetched_at"])))
    specs_table = ('<div class="table-shell"><table><tbody>' + "".join(specs_rows)
                   + "</tbody></table></div>")

    unit_rows = []
    if price_value and ram:
        unit_rows.append(_row(f"Price per GB of RAM",
                              f'<span class="price">{price_value / ram:.4f} {currency_code}</span> '
                              f'<span class="muted">= {price_value} {currency_code} ÷ {ram} GB</span>'))
    else:
        unit_rows.append(_row("Price per GB of RAM",
                              '<span class="muted">cannot be computed — the RAM figure is not published '
                              'next to this price</span>'))
    if price_value and vcpu:
        unit_rows.append(_row("Price per vCPU",
                              f'<span class="price">{price_value / vcpu:.4f} {currency_code}</span> '
                              f'<span class="muted">= {price_value} {currency_code} ÷ {vcpu} vCPU</span>'))
    else:
        unit_rows.append(_row("Price per vCPU",
                              '<span class="muted">cannot be computed — the vCPU count is not published '
                              'next to this price</span>'))
    if disk and ram:
        unit_rows.append(_row("Disk per GB of RAM",
                              f'{disk / ram:.1f} GB <span class="muted">= {disk} GB ÷ {ram} GB</span>'))
    unit_table = ('<div class="table-shell"><table><tbody>' + "".join(unit_rows)
                  + "</tbody></table></div>"
                  + '<p class="muted">Both inputs must come from the same plan block on the same page. '
                    'Where one is missing the cell says so instead of estimating it.</p>')

    siblings = [o for o in (provider_offers or []) if o.get("title") != offer.get("title")]
    if siblings:
        cmp_rows = []
        for other in sorted(siblings, key=lambda o: (o.get("price") is None, o.get("price") or 0)):
            other_price = money(other.get("price"), other.get("currency", currency))
            other_ram = other.get("ram_gb")
            per_gb = (f'{other["price"] / other_ram:.4f} {other.get("currency", "")}'
                      if other.get("price") and other_ram else '<span class="muted">-</span>')
            delta = ""
            if price_value and other.get("price"):
                diff = other["price"] - price_value
                delta = (f'<span class="muted">{diff:+.2f}</span>' if diff else
                         '<span class="muted">same</span>')
            cmp_rows.append(
                "<tr>"
                f'<td><a href="{escape(deal_page(site, other))}">{escape(other["title"])}</a></td>'
                f'<td class="price">{escape(other_price) if other_price else "not published"}</td>'
                f'<td>{escape(str(other_ram)) if other_ram else "-"}</td>'
                f'<td class="price">{per_gb}</td>'
                f'<td>{delta}</td>'
                "</tr>"
            )
        provider_table = (
            '<div class="table-shell"><table><thead><tr><th>Plan</th><th>Published price</th>'
            '<th>RAM (GB)</th><th>Per GB</th><th>vs this plan</th></tr></thead><tbody>'
            + "".join(cmp_rows) + "</tbody></table></div>"
            + f'<p class="muted">{len(siblings) + 1} {escape(offer["provider"])} plans were readable on the '
              f'source page. Differences are shown in {currency_code} without conversion.</p>'
        )
    else:
        provider_table = (
            f'<p class="muted">Only one {escape(offer["provider"])} plan could be read from the source page, '
            'so there is nothing to compare it against yet.</p>'
        )

    return render(
        template("deal.html"),
        {
            "lang": site["locale"],
            "brand": escape(site["brand"]),
            "head": head_block(meta, [schema, breadcrumb]),
            "nav": nav_block(site, []),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "deal_title": escape(offer["title"]),
            "provider": escape(offer["provider"]),
            "provider_url": provider_page(site, offer["provider"]),
            "price": escape(price_text) if price_text else '<span class="muted">not published on the source page</span>',
            "currency": escape(currency),
            "valid_until": escape(offer.get("valid_until", "")) or '<span class="muted">not stated</span>',
            "source_url": escape(offer["source_url"]),
            "fetched_at": escape(offer["fetched_at"]),
            "offer_url": escape(offer["offer_url"]),
            "specs_table": specs_table,
            "unit_table": unit_table,
            "provider_table": provider_table,
            "base_url": escape(site["base_url"]),
            "variants_note": (
                f'The provider page currently lists {variants} different prices for this plan; the lowest is shown here.'
                if variants > 1
                else ""
            ),
        },
    )


def build_compare(site: dict, offers: list[dict], providers: list[dict], generated_at: str) -> str:
    month = MONTHS[datetime.now(timezone.utc).month - 1]
    title = f"Compare {len(offers)} VPS plans by price ({month} {datetime.now(timezone.utc).year})"
    description = (
        f"Side-by-side price list of {len(offers)} VPS plans tracked from provider pages, sorted cheapest first. "
        f"Last read {generated_at}. Prices shown are the numbers published on each provider page."
    )
    item_list = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": title,
        "itemListElement": [
            {"@type": "ListItem", "position": index + 1,
             "url": deal_page(site, offer),
             "name": f'{offer["provider"]} {offer["title"]}'}
            for index, offer in enumerate(offers)
        ],
    }
    meta = {
        "canonical": compare_url(site),
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }
    return render(
        template("compare.html"),
        {
            "lang": site["locale"],
            "brand": escape(site["brand"]),
            "head": head_block(meta, [item_list]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "generated_at": generated_at,
            "rows": offer_rows(offers, site, {}, True),
            "offer_count": str(len(offers)),
        },
    )


# ------------------------------------------------------------------ 指南栏（补前十三页的缺口）

def guides_url(site: dict) -> str:
    return f'{site["base_url"]}/guide'


def guide_page(site: dict, guide: dict) -> str:
    return f'{site["base_url"]}/guide/{guide["slug"]}'


def _csv_cell(value) -> str:
    text = "" if value is None else str(value)
    if any(ch in text for ch in ',"\n'):
        return '"' + text.replace('"', '""') + '"'
    return text


def build_unit_price_csv(offers: list[dict]) -> tuple[str, int]:
    """可下载的比价表：每行一个套餐，规格和单价都来自抓到的公开页面。

    ::RULE{分母必须有出处⇒ram_gb / vcpu 缺失的行不写单价 写 not published}
    ::RULE{不换算货币⇒价格按源页面原币种原样输出}
    """
    header = [
        "provider", "plan", "price", "currency", "ram_gb", "vcpu", "disk_gb",
        "price_per_gb_ram", "price_per_vcpu", "unit_price_formula",
        "source_url", "fetched_at",
    ]
    lines = [",".join(header)]
    rows = 0
    for offer in sorted(offers, key=lambda o: (o["provider"], o.get("price") or 0)):
        price = offer.get("price")
        ram = offer.get("ram_gb")
        vcpu = offer.get("vcpu")
        per_gb = round(price / ram, 4) if price and ram else None
        per_vcpu = round(price / vcpu, 4) if price and vcpu else None
        formula = ""
        if per_gb is not None:
            formula = f'{price} {offer.get("currency", "")} / {ram} GB RAM'
        elif per_vcpu is not None:
            formula = f'{price} {offer.get("currency", "")} / {vcpu} vCPU'
        lines.append(",".join(_csv_cell(v) for v in [
            offer["provider"], offer["title"], price, offer.get("currency", ""),
            ram, vcpu, offer.get("disk_gb"), per_gb, per_vcpu, formula,
            offer["source_url"], offer["fetched_at"],
        ]))
        rows += 1
    return "\n".join(lines) + "\n", rows


def build_guide_index(
    site: dict, guides: list[dict], offers: list[dict], providers: list[dict], generated_at: str
) -> str:
    title = f'Cheap VPS guides — downloadable comparison table, unit prices, setup steps ({site["title"]})'
    description = (
        f"{len(guides)} ordered walkthroughs that fill what the top-ranking pages leave out: "
        "a comparison table you can download, prices broken down per GB of RAM and per vCPU, and numbered setup steps."
    )
    cards = []
    for guide in guides:
        cards.append(
            f'<div class="card"><h3><a href="{escape(guide_page(site, guide))}">{escape(guide["title"])}</a></h3>'
            f'<p class="muted">{escape(guide["answer"])}</p>'
            f'<p class="muted">gap filled: {escape(guide["gap"])}</p></div>'
        )
    offer_count = len([o for o in offers if o.get("price")])
    meta = _page_meta(site, "/guide", title, description)
    return render(
        template("guide.html"),
        {
            "lang": site["locale"],
            "brand": escape(site["brand"]),
            "head": head_block(meta, [_webpage_graph(site, "/guide", title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "h1": escape(f"Cheap VPS guides ({len(guides)})"),
            "answer": (
                f'<p class="lede">Each guide answers one question on this page. '
                f'Across {offer_count} tracked plans with a published price, here is what the provider pages '
                f'themselves do not tell you.</p>'
                f'<p><a class="cta" href="{escape(site["base_url"])}/downloads/unit-price.csv">Download the comparison table (CSV)</a></p>'
            ),
            "body": f'<div class="grid">{"".join(cards)}</div>',
            "gap_note": "This index fills nothing by itself; each guide below fills exactly one gap.",
            "sources": '<p class="muted">Sources: each guide lists its own.</p>',
        },
    )


def _bank_questions() -> list[str]:
    """搜索补全里抓到的真人问句（data/keyword-bank.json），只取问句形态的。

    文件不存在就是还没有词库：FAQ 的问题换成数据驱动的问法，答案口径不变。
    """
    path = ROOT / "data" / "keyword-bank.json"
    if not path.exists():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    return [item["query"] for item in payload.get("queries", []) if item.get("question")][:8]


def answer_from_data(guide: dict, offers: list[dict], expanded: str | None = None) -> str:
    """第一屏的答案必须带可核对的数字，数字只能来自抓到的数据。

    ::RULE{lede 里出现的每个数都能在 offers.json 或 CSV 里复算出来}
    自动页（guides.py 生成）自己带着按主题算好的答案，直接用；
    手写页没有当日主题，这里按缺口类型给一个汇总口径的答案。
    expanded：已经用当天的数字替换过占位符的答案（见 expand_live_tokens），
    不传就退回 guides.json 里存的那份——那份里可能还留着占位符，正常路径不会走到。
    """
    if guide.get("auto") and (expanded or guide.get("answer")):
        return expanded if expanded is not None else guide["answer"]
    priced = [o for o in offers if o.get("price") is not None]
    with_ram = [o for o in priced if o.get("ram_gb")]
    ranked = sorted(with_ram, key=lambda o: o["price"] / o["ram_gb"])
    providers = len({o["provider"] for o in priced})
    gap = guide.get("gap")
    if gap == "csv":
        return (
            f"{len(priced)} tracked plans across {providers} providers; {len(with_ram)} of them publish the RAM "
            f"figure their price is quoted next to, so those rows carry a computed per-GB number. "
            f"The CSV hands over the table itself."
        )
    if gap == "unitprice" and ranked:
        best = ranked[0]
        return (
            f"Cheapest RAM per unit today is {best['provider']} {best['title']} at "
            f"{best['price'] / best['ram_gb']:.4f} {best.get('currency', '')} per GB "
            f"({best['price']} {best.get('currency', '')} / {best['ram_gb']} GB) — computed only from numbers the "
            f"provider published. {len(with_ram)} of {len(priced)} priced plans can be ranked at all."
        )
    if gap == "steps":
        cheapest = min(priced, key=lambda o: o["price"]) if priced else None
        cheapest_text = money(cheapest["price"], cheapest.get("currency", "USD")) if cheapest else "n/a"
        return (
            f"{len(priced)} tracked plans, cheapest at {cheapest_text} per month "
            f"({cheapest['provider']} {cheapest['title']}). Eight numbered steps from picking the plan to "
            f"logging in, each sourced to provider documentation."
            if cheapest
            else "No tracked plan currently publishes a price, so no step cost can be quoted."
        )
    return guide["answer"]


def _chart_html(*names: str, alt: str) -> str:
    """套图插进页面：文件不存在就什么都不插，绝不插一条坏链接。"""
    blocks = []
    for name in names:
        if not (SITE_DIR / "assets" / name).exists():
            continue
        blocks.append(
            f'<p><img src="/assets/{escape(name)}" alt="{escape(alt)}" '
            f'width="760" height="auto" loading="lazy" decoding="async" '
            f'style="max-width:100%;height:auto;border-radius:10px"></p>'
        )
    return "".join(blocks)


def related_guides_html(site: dict, guide: dict, guides: list[dict], limit: int = 6) -> str:
    """同题材互链：本页 → 指南索引 → 今天那篇 + 同一缺口的前几篇 + 另外两个缺口的入口。

    14 个指南页原来只靠 sitemap 串起来，页面上彼此不指路。这里把最近的几篇连起来，
    让读者和爬虫都能顺着走。
    """
    others = [row for row in guides if row.get("slug") != guide.get("slug")]
    same_gap = [row for row in others if row.get("gap") == guide.get("gap")][-3:]
    by_date = sorted(others, key=lambda row: row.get("published", ""), reverse=True)[:2]
    picks: list[dict] = []
    for row in same_gap + by_date:
        if row not in picks:
            picks.append(row)
    items = [
        f'<li><a href="{escape(guide_page(site, row))}">{escape(row["title"])}</a></li>'
        for row in picks[:limit]
    ]
    items.append(f'<li><a href="{escape(guides_url(site))}">All guides ({len(guides)})</a></li>')
    items.append(
        f'<li><a href="{escape(site["base_url"])}/downloads/unit-price.csv">Download the price table (CSV)</a></li>'
    )
    return '<h2>More on this site</h2><ul>' + "".join(items) + "</ul>"


def updated_line(guide: dict, generated_at: str) -> str:
    """人眼可见的更新时间。

    对标的三家都把"什么时候更新的"写在正文里（lowendbox 同一页写了三个月份），
    我们原来只在 HTML head 里有日期，读者看不到。这里照实写两个日期：这篇什么时候发的、
    这些数字什么时候重新读的。
    """
    published = (guide.get("published") or generated_at)[:10]
    return (
        f'<p class="muted">Published {escape(published)} · prices last read from the providers '
        f'{escape(generated_at)} (UTC).</p>'
    )


def guide_focus(guide: dict, offers: list[dict]) -> str | None:
    """这篇指南的正文只排哪一家；排全站就返回 None。

    没在 guides.json 里加字段，而是从标题里认出厂商名：自动生成的标题把主题厂商写在标题里
    （csv 页是 "- <厂商> plans"、unitprice 页是 ": <厂商> -"、steps 页是 "steps: <厂商> plan"），
    手写页和 queue 页标题里没有厂商名。这样不用改数据文件，老页面也照样认得出。

    口径原则：FAQ 只答本页表格里那批行，认不出厂商的页面才用全站口径。
    """
    names = {o["provider"] for o in offers}
    title = guide.get("title", "")
    hits = [name for name in names if name in title]
    return hits[0] if len(hits) == 1 else None


# queue 页的标题形状固定（guides.py 的 build_queue_entry 生成），冒号后面是队列里的词，
# 标题本身说明了这一页排的是哪一批行：按磁盘单价排 / 按内存单价排 / 按月费排。
_QUEUE_TITLE_FIELDS = (
    ("Cheapest VPS disk per TB:", "disk_gb"),
    ("Cheapest VPS RAM per GB:", "ram_gb"),
    ("Cheapest tracked VPS plans:", None),
)


def guide_scope_offers(guide: dict, offers: list[dict]) -> list[dict]:
    """这一页正文真正排的那批行——FAQ 就答这批，不答全站。

    两种页面各有各的口径：厂商页只排一家（标题里有厂商名），queue 页按标题里写的那个维度
    筛过一遍（只排公布了硬盘/内存的那批）。都不是的（手写常青页）才用全站口径——
    那几页本来就横着看全站数据，答全站才是对的。这里只做筛选，不新增任何数字来源。
    """
    title = guide.get("title", "")
    for prefix, field in _QUEUE_TITLE_FIELDS:
        if title.startswith(prefix):
            if field is None:
                return [o for o in offers if o.get("price") is not None]
            return [o for o in offers if o.get("price") is not None and o.get(field)]
    focus = guide_focus(guide, offers)
    if focus:
        return [o for o in offers if o["provider"] == focus]
    return offers


# 手写常青页横着看全站数据（三页同行集），给各自一句范围说法，答案才不会一字不差。
_HANDWRITTEN_SCOPE = {
    "vps-comparison-table-csv": "in the downloadable comparison table",
    "how-to-buy-and-connect-a-cheap-vps": "across the plans these steps cover",
    "how-vps-pricing-works": "across the plans used in this explainer",
}


def guide_scope_phrase(guide: dict, offers: list[dict]) -> str:
    """这一页的范围，写成一个能接在句子任何位置的状语，写进 FAQ 答案里。

    必须能区分同类的两页，否则两页的 FAQ 又会一字不差：
      - queue 页只按维度筛行，两页"按月费排"的 queue 页行集是一样的 → 带上队列里那个词；
      - 自动页按厂商轮换，同一家会隔几天再轮到一次（IONOS 的 csv 页来过两次、
        Hostwinds 的单价页来过两次），行集也一样 → 带上这一页自己的发布日期。
        说"这一页"而不是"这一天的价格"：页面上排的就是这一页的表，价格是构建时抓的，
        不该暗示数字取自那一天。
    """
    title = guide.get("title", "")
    for prefix, _ in _QUEUE_TITLE_FIELDS:
        if title.startswith(prefix):
            term = title[len(prefix):].split(" - ", 1)[0].strip()
            return f'in the "{term}" shortlist' if term else "in this shortlist"
    focus = guide_focus(guide, offers)
    if not focus:
        return _HANDWRITTEN_SCOPE.get(guide.get("slug", ""), "among the tracked plans")
    snapshot = (guide.get("published") or "")[:10]
    if guide.get("auto") and snapshot:
        return f"on the {snapshot} {focus} page"
    return f"on the {focus} plan list"


def build_guide(
    site: dict, guide: dict, offers: list[dict], providers: list[dict], generated_at: str,
    guides: list[dict] | None = None,
) -> str:
    # 每一篇只补一个缺口，正文在 data/guides.json 里给定（自动页由 guides.py 生成）。
    # 这里不再按 gap 现编内容，避免出现"同一份数据被渲染成两种说法"。
    # 正文里全站口径的数字是占位符，按**今天**的抓取结果填（见 live_counts），
    # 否则页面上的表格行数和同一页 FAQ / CSV / 页脚日期会各说各话。
    body = expand_live_tokens(guide.get("body_html", ""), offers)
    answer = expand_live_tokens(guide.get("answer", ""), offers)
    if re.search(r'href="[^"]*(/deal/|source_url)', body):
        raise SystemExit(f'guide {guide["slug"]} must not link to per-offer pages; bodies stay data-free')
    if not body:
        raise SystemExit(f'guide {guide["slug"]} has no body_html; refusing to publish an empty page')

    title = f'{guide["title"]} — {site["title"]}'
    meta = {
        "canonical": guide_page(site, guide),
        "locale": site["locale"],
        "title": title,
        "description": answer,
        "brand": site["brand"],
        "og_type": "article",
        "og_image": site["og_image"],
    }
    article = {
        "@context": "https://schema.org",
        "@type": "TechArticle",
        "headline": guide["title"],
        "description": answer,
        "url": guide_page(site, guide),
        # 自动页自己有发布日期：用它，别用构建时间——否则每重建一次"发布日"就变一次。
        "datePublished": (guide.get("published") or generated_at)[:10],
        "dateModified": generated_at[:10],
        "isPartOf": {"@type": "WebSite", "name": site["title"], "url": home_url(site)},
    }
    breadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": site["title"], "item": home_url(site)},
            {"@type": "ListItem", "position": 2, "name": "Guides", "item": guides_url(site)},
            {"@type": "ListItem", "position": 3, "name": guide["title"], "item": guide_page(site, guide)},
        ],
    }
    sources = "".join(
        f'<li><a href="{escape(item["url"])}" rel="nofollow noopener" target="_blank">{escape(item["label"])}</a>'
        f' — read {escape(generated_at)}</li>'
        for item in guide.get("sources", [])
    )
    # T4：一问一答。问题来自搜索补全里的真人问句，答案全部由今天抓到的数字现算。
    # FAQ 只答**这一页表格里排的那批行**（见 guide_scope_offers / guide_scope_phrase）：
    # 厂商页只答那一家，queue 页只答标题里那个维度筛出来的那批。
    # 原来这里传的是全站 offers，于是 19 个指南页的 5 问 5 答一字不差，
    # 可见文本和 FAQPage 两份都一样，页面之间互相判成重复。
    faqs = frequently_asked(
        guide_scope_offers(guide, offers),
        _bank_questions(),
        guide_scope_phrase(guide, offers),
    )
    faq_html = ""
    extra_jsonld = [article, breadcrumb]
    # T5 套图：单价页插"每 GB 最便宜"的图，主题厂商有专属图就一起插。
    chart_html = ""
    if guide.get("gap") == "unitprice":
        # 标题形如 "Cheapest VPS per GB of RAM: Hostwinds - ..."，冒号后面就是主题厂商。
        focus = guide.get("title", "").split(":", 1)[1].split("-")[0].strip() if ":" in guide.get("title", "") else ""
        chart_html = _chart_html(
            "per-gb-cheapest.svg",
            f"per-gb-{slugify(focus)}.svg" if focus else "",
            alt=f'Monthly price per GB of RAM, computed from published prices ({guide["title"]})',
        )
        chart_html = chart_html + _chart_html(
            f"monthly-vs-ram-{slugify(focus)}.svg" if focus else "",
            alt=f'What the monthly fee buys at {focus}',
        )
    if faqs:
        rows = "".join(
            f'<h3>{escape(item["question"])}</h3><p>{escape(item["answer"])}</p>'
            + (f'<p class="muted">asked as: {escape(item["asked_as"])}</p>' if item.get("asked_as") else "")
            for item in faqs
        )
        faq_html = f'<h2>Questions this page answers</h2>{rows}'
        extra_jsonld.append({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
                {"@type": "Question", "name": item["question"],
                 "acceptedAnswer": {"@type": "Answer", "text": item["answer"]}}
                for item in faqs
            ],
        })
    return render(
        template("guide.html"),
        {
            "lang": site["locale"],
            "brand": escape(site["brand"]),
            "head": head_block(meta, extra_jsonld),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "h1": escape(guide["title"]),
            "answer": f'<p class="lede">{escape(answer_from_data(guide, offers, answer))}</p>' + chart_html,
            "body": body + faq_html + related_guides_html(site, guide, guides or []),
            "updated": updated_line(guide, generated_at),
            "gap_note": escape(guide["gap_note"]),
            "sources": f'<h2>Sources</h2><ul>{sources}</ul>' if sources else "",
        },
    )


# ------------------------------------------------------------------ 必备三页 + 404

def _page_meta(site: dict, path: str, title: str, description: str) -> dict:
    return {
        "canonical": f'{site["base_url"]}{path}',
        "locale": site["locale"],
        "title": title,
        "description": description,
        "brand": site["brand"],
        "og_type": "website",
        "og_image": site["og_image"],
    }


def _webpage_graph(site: dict, path: str, title: str, description: str) -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": title,
        "description": description,
        "url": f'{site["base_url"]}{path}',
        "isPartOf": {"@type": "WebSite", "name": site["title"], "url": f'{site["base_url"]}/'},
    }


def build_about(site: dict, providers: list[dict], generated_at: str,
                offers: list[dict] | None = None, guide_count: int = 0) -> str:
    path = "/about"
    title = f'About {site["title"]}'
    description = (
        f'{site["title"]} is an independent tracker of VPS prices published by hosting providers. '
        "Every number links back to the provider page it came from. Written and maintained by an independent developer."
    )
    # 自述必须与事实一致：只有真的接了联盟/广告才那么写，否则照实说没有。
    affiliate_live = any((row.get("affiliate_url") or "").strip() for row in providers)
    if affiliate_live:
        funding = (
            "<ul>"
            "<li><strong>Affiliate links.</strong> Some outbound links to providers are affiliate links.</li>"
            "<li><strong>Commission.</strong> If you sign up through one of those links, this site may earn a "
            "commission from the provider. It costs you nothing extra.</li>"
            "</ul>"
        )
    else:
        funding = (
            "<ul>"
            "<li><strong>No affiliate links are active yet.</strong> Outbound links to providers are currently "
            "plain links with no tracking parameter, so no commission is earned from them.</li>"
            "<li><strong>No advertising is shown.</strong> No ad network script is loaded on these pages.</li>"
            "</ul>"
            "<p>This site is self-funded and run as an independent project. If affiliate links are enabled later, "
            "this section will say so before they go live.</p>"
        )
    offer_count = len([o for o in (offers or []) if o.get("price") is not None])
    meta = _page_meta(site, path, title, description)
    return render(
        template("about.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, path, title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "site_title": escape(site["title"]),
            "repo_url": escape(site["repo_url"]),
            "base_url": escape(site["base_url"]),
            "funding": funding,
            "offer_count": str(offer_count),
            "provider_count": str(len(providers)),
            "guide_count": str(guide_count),
        },
    )


def build_methodology(site: dict, providers: list[dict], generated_at: str) -> str:
    path = "/methodology"
    title = f'How this site reads prices - {site["title"]}'
    description = (
        "The exact method behind every number on this site: which page is fetched, how a monthly plan price is "
        "separated from per-hour rates and fees, how per-GB figures are computed, and what is never estimated."
    )
    meta = _page_meta(site, path, title, description)
    return render(
        template("methodology.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, path, title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "base_url": escape(site["base_url"]),
        },
    )


def build_privacy(site: dict, providers: list[dict], generated_at: str) -> str:
    path = "/privacy"
    title = f'Privacy Policy - {site["title"]}'
    description = (
        "What data this site does and does not handle: third-party advertising, affiliate links, "
        "the analytics that are actually installed, no accounts and no forms."
    )
    meta = _page_meta(site, path, title, description)
    # 广告与联盟两段必须与事实一致：没接就写没接。联盟审核最看重的就是披露是否真实。
    if affiliate_live(providers):
        affiliate_section = (
            "<p>Some outbound links are affiliate links. If you follow one and sign up with the provider, this "
            "site may earn a commission. Affiliate links may carry a referral parameter so the provider can "
            "attribute the visit. Commission never changes the prices shown on this site or which plans are "
            "listed.</p>"
        )
    else:
        affiliate_section = (
            "<p><strong>No affiliate links are active on this site at present.</strong> Outbound links to hosting "
            "providers are plain links: they carry no referral parameter, and no commission is earned when you "
            "follow them. This section will be updated before any affiliate link is enabled.</p>"
        )
    advertising_section = (
        "<p><strong>No advertising is shown on this site.</strong> No advertising network script is loaded on "
        "these pages. If that changes, this policy will be updated first and the change will be visible on the "
        "date at the top of this page.</p>"
    )
    # 隐私政策必须与"实际装了什么"一致：装了 GA4 就不能再写"没有任何统计"。
    if VERIFY.get("ga4"):
        analytics_sentence = (
            "<strong>One analytics script is installed.</strong> This site uses Google Analytics 4 "
            f"({escape(VERIFY['ga4'])}) to count visits and page views. It sets cookies and processes "
            "your IP address and request data under Google's privacy policy."
        )
        analytics_detail = (
            "<h2>Google Analytics 4</h2>"
            f"<p>The measurement ID in use is <code>{escape(VERIFY['ga4'])}</code>. It is loaded on every page. "
            "Google acts as a processor for this data; see "
            '<a href="https://policies.google.com/privacy" rel="noopener" target="_blank">policies.google.com/privacy</a>. '
            "You can block it with any content blocker or browser setting without losing access to the site.</p>"
        )
    else:
        analytics_sentence = (
            "<strong>No first-party analytics.</strong> No analytics or tracking script of our own is installed, "
            "and no first-party cookies are set."
        )
        analytics_detail = ""
    return render(
        template("privacy.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, path, title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "site_title": escape(site["title"]),
            "base_url": site["base_url"],
            "generated_date": generated_at[:10],
            "analytics_sentence": analytics_sentence,
            "advertising_section": advertising_section,
            "affiliate_section": affiliate_section,
            "analytics_detail": analytics_detail,
        },
    )


def build_contact(site: dict, providers: list[dict], generated_at: str) -> str:
    path = "/contact"
    title = f'Contact - {site["title"]}'
    description = "How to reach the site: email contact@vpsdealsradar.com for price corrections, provider suggestions and privacy questions."
    meta = _page_meta(site, path, title, description)
    return render(
        template("contact.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, [_webpage_graph(site, path, title, description)]),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "base_url": site["base_url"],
        },
    )


def build_404(site: dict, providers: list[dict], generated_at: str) -> str:
    title = f'404 - page not found - {site["title"]}'
    meta = _page_meta(site, "/404", title, "There is no page at that address.")
    meta["canonical"] = f'{site["base_url"]}/404'
    return render(
        template("404.html"),
        {
            "lang": site["locale"],
            "head": head_block(meta, []),
            "nav": nav_block(site, providers),
            "footer": footer_block(site, generated_at),
            "title": escape(title),
            "brand": escape(site["brand"]),
            "base_url": site["base_url"],
        },
    )


# ------------------------------------------------------------------ 主流程

def main() -> int:
    global ASSET_V
    config = load_config()
    site_cfg = config["site"]
    payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))

    base_url = "https://" + site_cfg["domain"].rstrip("/")
    site = {
        "brand": site_cfg.get("brand", "vps-deals"),
        "title": site_cfg.get("title", "VPS Deals Radar"),
        "tagline": site_cfg.get("tagline", ""),
        "locale": site_cfg.get("locale", "en-US"),
        "domain": site_cfg["domain"],
        "base_url": base_url,
        "og_image": site_cfg.get("og_image", f"{base_url}/og.png"),
        "repo_url": site_cfg.get("repo", ""),
    }
    offers = payload["offers"]
    variants: dict[tuple, int] = {}
    offers, variants = collapse_offers(offers)
    providers = payload["providers"]
    by_name = {row["name"]: row for row in providers}
    global PROVIDERS_CTX
    PROVIDERS_CTX = providers
    generated_at = payload["generated_at"]

    SITE_DIR.mkdir(parents=True, exist_ok=True)
    (SITE_DIR / "provider").mkdir(exist_ok=True)
    (SITE_DIR / "deal").mkdir(exist_ok=True)
    (SITE_DIR / "assets").mkdir(exist_ok=True)
    (SITE_DIR / "guide").mkdir(exist_ok=True)
    (SITE_DIR / "downloads").mkdir(exist_ok=True)

    ASSET_V = re.sub(r"[^0-9A-Za-z]", "", generated_at) or "0"
    VERIFY["gsc"] = (site_cfg.get("gsc_verification") or "").strip()
    VERIFY["ga4"] = (site_cfg.get("ga4_measurement_id") or "").strip()
    if VERIFY["ga4"] and not re.fullmatch(r"G-[A-Z0-9]{4,}", VERIFY["ga4"]):
        raise SystemExit(f'ga4_measurement_id 看起来不是 GA4 衡量 ID：{VERIFY["ga4"]!r}（应形如 G-XXXXXXXXXX）')
    asset_paths = []
    if ASSET_DIR.exists():
        for asset in sorted(ASSET_DIR.iterdir()):
            if asset.is_file():
                (SITE_DIR / "assets" / asset.name).write_text(asset.read_text(encoding="utf-8"), encoding="utf-8")
                asset_paths.append(f"/assets/{asset.name}")

    # 社交分享大图（真 PNG，构建时用标准库生成；og:image 指向它，不再是一条坏链接）
    build_og_image(site, SITE_DIR / "og.png")
    asset_paths.append("/og.png")

    # 指南清单提前载入：about 页要引用当期篇数，页脚导航也要用
    guides = json.loads(GUIDES_PATH.read_text(encoding="utf-8")) if GUIDES_PATH.exists() else []

    # T5 套图：把抓到的价格画成 SVG（纯文本、零依赖），文件名由数据决定。
    chart_names = chart_assets.build_all(offers, SITE_DIR / "assets")
    asset_paths += [f"/assets/{name}" for name in chart_names]

    written = []
    for name, html in {
        "index.html": build_index(site, offers, providers, generated_at),
        "compare.html": build_compare(site, offers, providers, generated_at),
        "about.html": build_about(site, providers, generated_at, offers, len(guides)),
        "methodology.html": build_methodology(site, providers, generated_at),
        "privacy.html": build_privacy(site, providers, generated_at),
        "contact.html": build_contact(site, providers, generated_at),
        "404.html": build_404(site, providers, generated_at),
    }.items():
        (SITE_DIR / name).write_text(html, encoding="utf-8")
        written.append(name)

    grouped = group_offers(offers)
    for provider in providers:
        html = build_provider(site, provider, grouped.get(provider["name"], []), generated_at)
        path = SITE_DIR / "provider" / f"{slugify(provider['name'])}.html"
        path.write_text(html, encoding="utf-8")
        written.append(f"provider/{path.name}")

    for offer in offers:
        html = build_deal(site, offer, generated_at,
                            variants.get((offer["provider"], offer["title"].lower()), 1),
                            grouped.get(offer["provider"], []))
        path = SITE_DIR / "deal" / f"{offer_slug(offer)}.html"
        path.write_text(html, encoding="utf-8")
        written.append(f"deal/{path.name}")

    # 厂商改型号或改套餐名之后，旧 slug 的 deal 页会变成孤儿页：线上已被 _worker.js
    # 的白名单判 404，文件却还留在 site/ 里被每次部署一起上传。deal 页全部由本次 offers
    # 生成，所以直接和本次产出的集合对齐；和指南那段的清理保持同一套做法。
    deal_keep = {f"{offer_slug(offer)}.html" for offer in offers}
    for stale in sorted((SITE_DIR / "deal").glob("*.html")):
        if stale.name not in deal_keep:
            stale.unlink()
            written.append(f"removed stale deal/{stale.name}")

    # 厂商从 site.ilang 删掉之后，它的 provider 页同样会变成孤儿页（deal 页上面清了，
    # provider 页当初漏了，自测 TEST2 抓到过）：和本次 providers 集合对齐，同一套做法。
    provider_keep = {f"{slugify(provider['name'])}.html" for provider in providers}
    for stale in sorted((SITE_DIR / "provider").glob("*.html")):
        if stale.name not in provider_keep:
            stale.unlink()
            written.append(f"removed stale provider/{stale.name}")

    # 可下载的比价表：三家里没有任何一家提供这种文件，这是这个词最集中的缺口。
    csv_body, csv_rows = build_unit_price_csv(offers)
    (SITE_DIR / "downloads" / "unit-price.csv").write_text(csv_body, encoding="utf-8")

    # 指南栏：每篇只补一个缺口，内容由 data/guides.json 提供，渲染是确定性的。
    # 清掉已经不存在的指南页，否则旧日期的页面会一直留在线上的目录里变成孤儿页。
    # 只删"带日期后缀的自动页"（csv-YYYY-MM-DD-n / unitprice-... / steps-...），手写页不碰。
    keep = {f'{guide["slug"]}.html' for guide in guides}
    for stale in sorted((SITE_DIR / "guide").glob("*.html")):
        if stale.name in keep:
            continue
        if re.match(r"^(csv|unitprice|steps)-\d{4}-\d{2}-\d{2}-\d+\.html$", stale.name):
            stale.unlink()
            written.append(f"removed stale guide/{stale.name}")
    (SITE_DIR / "guide.html").write_text(
        build_guide_index(site, guides, offers, providers, generated_at), encoding="utf-8"
    )
    written.append("guide.html")
    for guide in guides:
        html = build_guide(site, guide, offers, providers, generated_at, guides)
        path = SITE_DIR / "guide" / f'{guide["slug"]}.html'
        path.write_text(html, encoding="utf-8")
        written.append(f"guide/{path.name}")

    urls = [home_url(site), compare_url(site)]
    urls += [f"{base_url}/about", f"{base_url}/methodology", f"{base_url}/privacy", f"{base_url}/contact"]
    urls += [provider_page(site, row["name"]) for row in providers]
    urls += [deal_page(site, offer) for offer in offers]
    # 可下载的 CSV 也进 sitemap：它是站上唯一的可下载资产页，值得被抓到
    urls += [f"{base_url}/downloads/unit-price.csv"]
    urls += [guides_url(site)]
    urls += [guide_page(site, guide) for guide in guides]
    # 指南页用各自的发布日期做 lastmod（自动页有 published），其余用本次构建时间。
    lastmod_for = {guide_page(site, guide): guide.get("published", generated_at) for guide in guides}
    sitemap = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in urls:
        lastmod = lastmod_for.get(url, generated_at)
        sitemap.append(f"  <url><loc>{escape(url)}</loc><lastmod>{escape(lastmod)}</lastmod></url>")
    sitemap.append("</urlset>")
    (SITE_DIR / "sitemap.xml").write_text("\n".join(sitemap) + "\n", encoding="utf-8")
    (SITE_DIR / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\n\nSitemap: {base_url}/sitemap.xml\n", encoding="utf-8"
    )
    # 合法路径白名单：由这次构建实际写出的页面生成，交给 _worker.js 判 404。
    # 不写死在这里，就不会出现"加了页面却忘了改 404 逻辑"。
    valid_paths = ["/", "/compare", "/about", "/methodology", "/privacy", "/contact", "/sitemap.xml", "/robots.txt", "/guide"]
    valid_paths += asset_paths
    valid_paths.append("/downloads/unit-price.csv")
    valid_paths += [f"/provider/{slugify(row['name'])}" for row in providers]
    valid_paths += [f"/deal/{offer_slug(offer)}" for offer in offers]
    valid_paths += [f'/guide/{guide["slug"]}' for guide in guides]
    (SITE_DIR / "_worker.js").write_text(
        WORKER_TEMPLATE.replace("__CANONICAL_HOST__", site_cfg["domain"]).replace(
            "__VALID_PATHS__", json.dumps(valid_paths)
        ),
        encoding="utf-8",
    )

    # 结构化数据自查：Google 对 Product 的必填字段是 name + offers，对 Offer 要 price。
    # 发一个"没有 offers 的 Product"或"没有 price 的 Offer"就是 Search Console 里的硬错误
    # （2026-10-02 GSC 报的就是这一类）。这里在构建时直接拦下，宁可构建失败也不发出去。
    problems = audit_structured_data(SITE_DIR)
    if problems:
        raise SystemExit("结构化数据自查未通过，已阻止构建：\n  " + "\n  ".join(problems[:10]))

    print(
        f"wrote {len(written)} pages + sitemap.xml({len(urls)} urls) + robots.txt + "
        f"_worker.js(301 canonical host, real 404, {len(valid_paths)} allowed paths)"
    )
    print(f"data snapshot {generated_at} | offers {len(offers)} | providers {len(by_name)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
